export type TwseDividendInfo={symbol:string;name:string;exDate:string;recordDate:string;payDate:string;dividend:number;lastBuyDate:string;source:string};
const URL='https://www.twse.com.tw/zh/ETFortune/dividendList';
const HOLIDAY_URL=(year:number)=>`https://www.twse.com.tw/holidaySchedule/holidaySchedule?response=html&queryYear=${year-1911}`;
const holidayCache=new Map<number,Set<string>>();
const rocToIso=(s:string)=>{const m=s.match(/(\d{3})年(\d{2})月(\d{2})日/);return m?`${Number(m[1])+1911}-${m[2]}-${m[3]}`:''};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const previousTradingDay=(dateIso:string)=>{if(!dateIso)return '';const d=new Date(`${dateIso}T12:00:00`);do{d.setDate(d.getDate()-1)}while(d.getDay()===0||d.getDay()===6);return iso(d)};
const clean=(html:string)=>html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
async function closedMarketDays(year:number){const cached=holidayCache.get(year);if(cached)return cached;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(HOLIDAY_URL(year),{headers:{Accept:'text/html'},signal:controller.signal});if(!r.ok)throw new Error(`TWSE 休市資料 HTTP ${r.status}`);const html=await r.text();const closed=new Set<string>();for(const match of html.matchAll(/<tr[\s\S]*?<\/tr>/gi)){const row=clean(match[0]);const date=row.match(/\b20\d{2}-\d{2}-\d{2}\b/)?.[0];if(!date)continue;const explicitlyOpen=/(開始交易日|最後交易日|開始交易|最後交易)/.test(row);if(!explicitlyOpen)closed.add(date)}holidayCache.set(year,closed);return closed}finally{clearTimeout(timer)}}
export async function previousTwseTradingDay(dateIso:string){if(!dateIso)return '';const d=new Date(`${dateIso}T12:00:00`);for(let guard=0;guard<20;guard++){d.setDate(d.getDate()-1);if(d.getDay()===0||d.getDay()===6)continue;try{const closed=await closedMarketDays(d.getFullYear());if(closed.has(iso(d)))continue}catch{return previousTradingDay(dateIso)}return iso(d)}return previousTradingDay(dateIso)}
function parseText(text:string,symbol:string):TwseDividendInfo|null{const i=text.indexOf(symbol);if(i<0)return null;const chunk=text.slice(i,i+900);const name=(chunk.match(new RegExp(`${symbol}\\s+([^0-9]{2,50}?)\\s+\\d{3}年`))?.[1]||symbol).trim();const dates=[...chunk.matchAll(/\d{3}年\d{2}月\d{2}日/g)].map(m=>rocToIso(m[0]));const nums=[...chunk.matchAll(/\s(\d+(?:\.\d+)?)\s/g)].map(m=>Number(m[1])).filter(n=>n>=0&&n<100);const exDate=dates[0]||'',recordDate=dates[1]||'',payDate=dates[2]||'';const dividend=nums.find(n=>n>0&&n<20)??0;return {symbol,name,exDate,recordDate,payDate,dividend,lastBuyDate:previousTradingDay(exDate),source:'臺灣證券交易所 ETF e添富'};}
async function fetchText(){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(URL,{headers:{Accept:'text/html'},signal:controller.signal});if(!r.ok)throw new Error(`TWSE 配息資料 HTTP ${r.status}`);return clean(await r.text())}finally{clearTimeout(timer)}}
async function resolveLastBuy(info:TwseDividendInfo|null){if(!info||!info.exDate)return info;return {...info,lastBuyDate:await previousTwseTradingDay(info.exDate)}}
export async function fetchTwseDividend(symbol:string):Promise<TwseDividendInfo|null>{return resolveLastBuy(parseText(await fetchText(),symbol.toUpperCase()));}
export async function fetchTwseDividends(symbols:string[]):Promise<Record<string,TwseDividendInfo|null>>{const text=await fetchText();const unique=[...new Set(symbols.map(x=>x.toUpperCase()))];const pairs=await Promise.all(unique.map(async symbol=>[symbol,await resolveLastBuy(parseText(text,symbol))] as const));return Object.fromEntries(pairs);}
