import React, { useEffect, useMemo, useRef, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import Svg, { Circle, Line, Path, Polygon, Polyline, Rect, Text as SvgText } from 'react-native-svg';
import type { Holding } from '../data/portfolio';
import type { DividendEvent } from '../screens/DividendCalendarScreen';
import type { AppSettings, DailySnapshot } from '../storage/appStorage';
import type { TwseQuote } from '../services/twse';
import { fetchTwseOhlcvHistory, TwseOhlcvPoint } from '../services/twseHistory';
import type { IntradayPnlPoint, LedgerEntry, V3ChartConfig, V3Preferences } from './model';
import { calculateDividendIncome, calculateHoldingView, calculatePortfolioView } from './engine';
import {rendererNode,resolveRendererColor} from '../ui/universalRegistry';

type Context={holdings:Holding[];quotes:Record<string,Partial<TwseQuote>>;ledger:LedgerEntry[];dividends:DividendEvent[];cashBalance:number;dailySnapshots:DailySnapshot[];intradayPnlPoints:IntradayPnlPoint[];appSettings?:AppSettings;activeSymbol?:string};
type Point={label:string;value:number};
const W=360;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const valid=(n:any)=>Number.isFinite(Number(n));
const moneyShort=(v:number)=>Math.abs(v)>=1e6?`${(v/1e6).toFixed(1)}M`:Math.abs(v)>=1e3?`${(v/1e3).toFixed(1)}K`:Math.round(v).toLocaleString('zh-TW');
const alpha=(hex:string,a:number)=>{const h=hex.replace('#','');if(!/^[0-9a-fA-F]{6}$/.test(h))return `rgba(255,255,255,${a})`;const n=parseInt(h,16);return `rgba(${n>>16},${(n>>8)&255},${n&255},${a})`};
const palette=(prefs:V3Preferences,cfg:V3ChartConfig)=>{const primary=cfg.colorMode==='custom'?(cfg.primaryColor||prefs.accentColor):prefs.accentColor;return {primary,positive:cfg.positiveColor||prefs.positiveColor,negative:cfg.negativeColor||prefs.negativeColor,series:cfg.seriesColors?.length?cfg.seriesColors:[primary,prefs.positiveColor,prefs.negativeColor,'#4CC9F0','#A78BFA','#F59E0B']};};
const metricValue=(row:any,metric:string)=>metric==='totalAssets'?Number(row.totalAssets??row.marketValue??0):Number(row[metric]??0);
const singleSeries=(cfg:V3ChartConfig,c:Context):Point[]=>{if(cfg.source==='intraday'){return c.intradayPnlPoints.slice(-Math.max(2,cfg.range||120)).map(x=>({label:x.time?.slice(0,5)||'',value:metricValue(x,cfg.metric)}));}return c.dailySnapshots.slice(-Math.max(2,cfg.range||30)).map(x=>({label:x.date.slice(5),value:metricValue(x,cfg.metric)}));};
const noData=(title:string,detail:string,height:number)=><View style={[st.noData,{height}]}><Text style={st.noDataTitle}>{title}</Text><Text style={st.noDataText}>{detail}</Text></View>;

function Grid({h,p=22,show=true}:{h:number;p?:number;show?:boolean}){if(!show)return null;return <>{[.25,.5,.75].map((r,i)=><Line key={i} x1={p} y1={p+(h-p*2)*r} x2={W-p} y2={p+(h-p*2)*r} stroke="rgba(255,255,255,.08)" strokeWidth="1"/>)}</>}
function AxisLabels({points,h,p=22,show=true}:{points:Point[];h:number;p?:number;show?:boolean}){if(!show||!points.length)return null;const idx=[0,Math.floor((points.length-1)/2),points.length-1];return <>{idx.map((i,n)=><SvgText key={`${i}-${n}`} x={p+i*(W-p*2)/Math.max(1,points.length-1)} y={h-4} fill="rgba(255,255,255,.42)" fontSize="8" textAnchor={n===0?'start':n===2?'end':'middle'}>{points[i]?.label||''}</SvgText>)}</>}
function XY({points,h,cfg,prefs,kind}:{points:Point[];h:number;cfg:V3ChartConfig;prefs:V3Preferences;kind:'line'|'area'|'bar'|'positiveBar'|'pnlTrend'|'scatter'}){if(points.length<2)return noData('資料累積中','此圖至少需要 2 筆真實資料。',h);const p=22;const colors=palette(prefs,cfg);const vals=points.map(x=>x.value);const min=Math.min(...vals,cfg.showZeroLine?0:Infinity),max=Math.max(...vals,cfg.showZeroLine?0:-Infinity);const span=Math.max(1,max-min);const xy=points.map((d,i)=>({x:p+i*(W-p*2)/Math.max(1,points.length-1),y:h-p-(d.value-min)/span*(h-p*2),...d}));const zeroY=h-p-(0-min)/span*(h-p*2);const poly=xy.map(q=>`${q.x},${q.y}`).join(' ');const area=`M ${xy[0].x} ${h-p} L ${xy.map(q=>`${q.x} ${q.y}`).join(' L ')} L ${xy[xy.length-1].x} ${h-p} Z`;const bw=Math.max(2,(W-p*2)/Math.max(3,points.length)*.62);const usePnl=kind==='positiveBar'||kind==='pnlTrend'||cfg.colorMode==='profitLoss';return <Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`} preserveAspectRatio="none"><Grid h={h} p={p} show={cfg.showGrid!==false}/>{cfg.showZeroLine&&zeroY>=p&&zeroY<=h-p?<Line x1={p} y1={zeroY} x2={W-p} y2={zeroY} stroke="rgba(255,255,255,.2)"/>:null}{kind==='bar'||kind==='positiveBar'?xy.map((q,i)=>{const base=clamp(zeroY,p,h-p),y=Math.min(q.y,base),bh=Math.max(1,Math.abs(q.y-base));return <Rect key={i} x={q.x-bw/2} y={y} width={bw} height={bh} rx={cfg.barRadius??4} fill={usePnl?(q.value>=0?colors.positive:colors.negative):colors.primary} opacity={.82}/>;}):kind==='scatter'?xy.map((q,i)=><Circle key={i} cx={q.x} cy={q.y} r={cfg.showPoints===false?3:4} fill={q.value>=0?colors.positive:colors.negative}/>):<>{kind==='area'||kind==='pnlTrend'?<Path d={area} fill={usePnl?(xy[xy.length-1].value>=0?colors.positive:colors.negative):colors.primary} fillOpacity={clamp((cfg.fillOpacity??14)/100,.04,.65)}/>:null}<Polyline points={poly} fill="none" stroke={usePnl?(xy[xy.length-1].value>=0?colors.positive:colors.negative):colors.primary} strokeWidth={cfg.lineWidth??3} strokeLinejoin="round" strokeLinecap="round"/>{cfg.showPoints!==false?xy.map((q,i)=><Circle key={i} cx={q.x} cy={q.y} r="2.6" fill={usePnl?(q.value>=0?colors.positive:colors.negative):colors.primary}/>):null}</>}<AxisLabels points={points} h={h} p={p} show={cfg.showAxis!==false}/></Svg>}
function Composition({c,cfg,prefs,h,donut=false}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number;donut?:boolean}){const colors=palette(prefs,cfg);const rows=c.holdings.map(hd=>({label:hd.symbol,value:Number(c.quotes[hd.symbol]?.price??hd.fallbackPrice??hd.avgCost??0)*hd.shares})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,8);const total=rows.reduce((s,x)=>s+x.value,0);if(!total)return noData('沒有持倉組成資料','圓餅／環形圖需要目前持倉市值。',h);const cx=150,cy=h/2,r=Math.min(72,h*.34),inner=donut?r*.56:0;let angle=-Math.PI/2;const arcs=rows.map((row,i)=>{const next=angle+row.value/total*Math.PI*2;const x1=cx+r*Math.cos(angle),y1=cy+r*Math.sin(angle),x2=cx+r*Math.cos(next),y2=cy+r*Math.sin(next);const ix1=cx+inner*Math.cos(angle),iy1=cy+inner*Math.sin(angle),ix2=cx+inner*Math.cos(next),iy2=cy+inner*Math.sin(next);const large=next-angle>Math.PI?1:0;const d=inner>0?`M ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2} L ${ix2} ${iy2} A ${inner} ${inner} 0 ${large} 0 ${ix1} ${iy1} Z`:`M ${cx} ${cy} L ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2} Z`;angle=next;return {d,row,color:colors.series[i%colors.series.length]};});return <View style={{height:h,flexDirection:'row',alignItems:'center'}}><Svg width="62%" height={h} viewBox={`0 0 220 ${h}`}>{arcs.map((a,i)=><Path key={i} d={a.d} fill={a.color} opacity={.86}/>)}</Svg>{cfg.showLegend!==false?<View style={{flex:1,gap:4}}>{rows.slice(0,5).map((row,i)=><Text key={row.label} style={st.legend}>{row.label} {(row.value/total*100).toFixed(1)}%</Text>)}</View>:null}</View>}
function MultiLine({c,cfg,prefs,h}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number}){const colors=palette(prefs,cfg);const snaps=c.dailySnapshots.slice(-Math.max(2,cfg.range||30));if(snaps.length<2)return noData('多折線資料不足','需要至少 2 日的 ETF 快照。',h);const syms=c.holdings.slice().sort((a,b)=>b.shares*Number(c.quotes[b.symbol]?.price??b.fallbackPrice??0)-a.shares*Number(c.quotes[a.symbol]?.price??a.fallbackPrice??0)).slice(0,4).map(x=>x.symbol);if(!syms.length)return noData('沒有 ETF 可比較','持有 ETF 後即可產生多折線比較。',h);const p=22;const all=snaps.flatMap(s=>syms.map(sym=>Number(s.holdings.find(x=>x.symbol===sym)?.totalPnl??0)));const min=Math.min(...all,0),max=Math.max(...all,0),span=Math.max(1,max-min);return <View style={{height:h}}><Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`} preserveAspectRatio="none"><Grid h={h} p={p} show={cfg.showGrid!==false}/>{syms.map((sym,si)=>{const pts=snaps.map((snap,i)=>{const v=Number(snap.holdings.find(x=>x.symbol===sym)?.totalPnl??0);return `${p+i*(W-p*2)/Math.max(1,snaps.length-1)},${h-p-(v-min)/span*(h-p*2)}`}).join(' ');return <Polyline key={sym} points={pts} fill="none" stroke={colors.series[si%colors.series.length]} strokeWidth={cfg.lineWidth??2.5}/>})}<AxisLabels points={snaps.map(x=>({label:x.date.slice(5),value:0}))} h={h} p={p} show={cfg.showAxis!==false}/></Svg>{cfg.showLegend!==false?<View style={st.legendRow}>{syms.map((x,i)=><Text key={x} style={st.legend}>{x}</Text>)}</View>:null}</View>}
function Stacked({c,cfg,prefs,h}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number}){const colors=palette(prefs,cfg);const snaps=c.dailySnapshots.slice(-Math.min(12,Math.max(2,cfg.range||12)));const syms=c.holdings.slice(0,5).map(x=>x.symbol);if(snaps.length<2||!syms.length)return noData('堆疊資料不足','需要每日 ETF 市值快照。',h);const p=22,bw=(W-p*2)/snaps.length*.62;const totals=snaps.map(s=>syms.reduce((sum,sym)=>sum+Number(s.holdings.find(x=>x.symbol===sym)?.marketValue??0),0));const max=Math.max(1,...totals);return <View style={{height:h}}><Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`} preserveAspectRatio="none"><Grid h={h} p={p} show={cfg.showGrid!==false}/>{snaps.map((snap,i)=>{let y=h-p;return syms.map((sym,si)=>{const v=Number(snap.holdings.find(x=>x.symbol===sym)?.marketValue??0);const bh=(h-p*2)*v/max;y-=bh;return <Rect key={`${i}-${sym}`} x={p+i*(W-p*2)/snaps.length+((W-p*2)/snaps.length-bw)/2} y={y} width={bw} height={Math.max(0,bh)} fill={colors.series[si%colors.series.length]} opacity={.82}/>})})}<AxisLabels points={snaps.map(x=>({label:x.date.slice(5),value:0}))} h={h} p={p} show={cfg.showAxis!==false}/></Svg></View>}
function Candle({c,cfg,prefs,h,history}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number;history:TwseOhlcvPoint[]}){const colors=palette(prefs,cfg);const symbol=c.activeSymbol||c.holdings[0]?.symbol;const q=symbol?c.quotes[symbol]:undefined;let rows=history.slice(-Math.max(2,Math.min(60,cfg.range||30)));if(!rows.length&&symbol){const o=Number(q?.open),hi=Number(q?.high),lo=Number(q?.low),close=Number(q?.price);if([o,hi,lo,close].every(Number.isFinite)&&hi>0&&lo>0)rows=[{date:String(q?.quoteDate||'今日'),open:o,high:hi,low:lo,close,volume:Number(q?.volume||0)}]};if(!symbol||!rows.length)return noData('K 線資料不足','正在等待 TWSE STOCK_DAY 歷史 OHLC；不會以假資料補圖。',h);const p=24,minP=Math.min(...rows.map(x=>x.low)),maxP=Math.max(...rows.map(x=>x.high)),span=Math.max(.01,maxP-minP),yy=(v:number)=>p+(maxP-v)/span*(h-p*2),step=(W-p*2)/Math.max(1,rows.length),bw=Math.max(2,Math.min(10,step*.56));return <Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`} preserveAspectRatio="none"><Grid h={h} p={p} show={cfg.showGrid!==false}/>{rows.map((r,i)=>{const cx=p+i*step+step/2,up=r.close>=r.open,col=up?colors.positive:colors.negative,yOpen=yy(r.open),yClose=yy(r.close);return <React.Fragment key={`${r.date}-${i}`}><Line x1={cx} y1={yy(r.high)} x2={cx} y2={yy(r.low)} stroke={col} strokeWidth="1.2"/><Rect x={cx-bw/2} y={Math.min(yOpen,yClose)} width={bw} height={Math.max(1.5,Math.abs(yOpen-yClose))} rx={Math.min(2,cfg.barRadius??2)} fill={up?alpha(col,.24):col} stroke={col} strokeWidth="1"/></React.Fragment>})}{cfg.showAxis!==false?<AxisLabels points={rows.map(x=>({label:x.date.length>=5?x.date.slice(5):x.date,value:x.close}))} h={h} p={p} show/>:null}</Svg>}
function Volume({c,cfg,prefs,h,history}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number;history:TwseOhlcvPoint[]}){if(history.length){const rows=history.slice(-Math.max(2,Math.min(80,cfg.range||30))).map(x=>({label:x.date.slice(5),value:x.volume}));return <XY points={rows} h={h} cfg={{...cfg,showZeroLine:true}} prefs={prefs} kind="bar"/>}const rows=c.holdings.map(x=>({label:x.symbol,value:Number(c.quotes[x.symbol]?.volume??0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,8);if(!rows.length)return noData('成交量資料不足','正在等待 TWSE STOCK_DAY 或即時成交量資料。',h);return <XY points={rows.length===1?[{...rows[0],label:''},{...rows[0]}]:rows} h={h} cfg={{...cfg,showZeroLine:true}} prefs={prefs} kind="bar"/>}
function Heatmap({c,cfg,prefs,h}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number}){const colors=palette(prefs,cfg);const rows=c.dailySnapshots.slice(-Math.max(7,cfg.range||30));if(!rows.length)return noData('熱力圖資料不足','需要每日損益快照。',h);const cols=7,cellW=(W-24)/cols,cellH=Math.min(28,(h-28)/Math.ceil(rows.length/cols));const max=Math.max(1,...rows.map(x=>Math.abs(x.todayPnl)));return <Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`}>{rows.map((r,i)=>{const x=12+(i%cols)*cellW,y=10+Math.floor(i/cols)*cellH;return <React.Fragment key={r.date}><Rect x={x} y={y} width={cellW-3} height={cellH-3} rx={4} fill={r.todayPnl>=0?colors.positive:colors.negative} opacity={.16+.72*Math.min(1,Math.abs(r.todayPnl)/max)}/>{cfg.showLabels?<SvgText x={x+3} y={y+cellH/2+3} fill="white" fontSize="7">{r.date.slice(8)}</SvgText>:null}</React.Fragment>})}</Svg>}
function Waterfall({c,cfg,prefs,h}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number}){const colors=palette(prefs,cfg);const m=calculatePortfolioView(c.holdings,c.quotes as any,c.cashBalance,c.ledger,c.dividends);const rows=[{label:'未實現',value:m.cashUnrealizedPnl},{label:'已實現',value:m.realizedCashPnl},{label:'配息',value:m.cumulativeDividends}];const totals:number[]=[];let acc=0;for(const r of rows){acc+=r.value;totals.push(acc)}const vals=[0,...totals];const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min);const p=28,bw=66,gap=(W-p*2-bw*3)/2,yy=(v:number)=>h-p-(v-min)/span*(h-p*2);let prev=0;return <Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`}><Grid h={h} p={p} show={cfg.showGrid!==false}/>{rows.map((r,i)=>{const next=totals[i],x=p+i*(bw+gap),y1=yy(prev),y2=yy(next),y=Math.min(y1,y2),bh=Math.max(2,Math.abs(y2-y1)),col=r.value>=0?colors.positive:colors.negative;const elem=<React.Fragment key={r.label}><Rect x={x} y={y} width={bw} height={bh} rx={cfg.barRadius??4} fill={col} opacity={.8}/>{i>0?<Line x1={x-gap} y1={y1} x2={x} y2={y1} stroke="rgba(255,255,255,.25)" strokeDasharray="3 3"/>:null}<SvgText x={x+bw/2} y={h-8} textAnchor="middle" fill="rgba(255,255,255,.55)" fontSize="8">{r.label}</SvgText></React.Fragment>;prev=next;return elem})}</Svg>}
function Progress({c,cfg,prefs,h}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number}){const colors=palette(prefs,cfg);const m=calculatePortfolioView(c.holdings,c.quotes as any,c.cashBalance,c.ledger,c.dividends);const target=Number(cfg.targetValue??c.appSettings?.goals.totalAssetsTarget??0);if(target<=0)return noData('尚未設定目標','請先設定總資產目標或圖表目標值。',h);const ratio=clamp(m.totalAssets/target,0,1);return <View style={{height:h,justifyContent:'center',paddingHorizontal:12}}><View style={st.progressTrack}><View style={[st.progressFill,{width:`${ratio*100}%`,backgroundColor:colors.primary}]}/></View><Text style={st.progressText}>{moneyShort(m.totalAssets)} / {moneyShort(target)}　{(ratio*100).toFixed(1)}%</Text></View>}
function Radar({c,cfg,prefs,h}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number}){const colors=palette(prefs,cfg);const hd=c.holdings.find(x=>x.symbol===(c.activeSymbol||c.holdings[0]?.symbol));if(!hd)return noData('雷達資料不足','請先選擇或持有一檔 ETF。',h);const totalMv=c.holdings.reduce((sum,x)=>sum+Number(c.quotes[x.symbol]?.price??x.fallbackPrice??0)*x.shares,0);const hm=calculateHoldingView(hd,c.quotes as any,c.ledger,c.dividends);const weight=totalMv>0?hm.marketValue/totalMv*100:0;const peers=c.holdings.map(x=>calculateHoldingView(x,c.quotes as any,c.ledger,c.dividends));const maxAbsRoi=Math.max(1,...peers.map(x=>Math.abs(x.cashRoi)));const maxAbsToday=Math.max(1,...peers.map(x=>Math.abs(x.todayPnlPct)));const maxYield=Math.max(1,...peers.map(x=>Math.abs(x.costYield)));const q=c.quotes[hd.symbol];const maxVol=Math.max(1,...c.holdings.map(x=>Number(c.quotes[x.symbol]?.volume??0)));const vals=[clamp((hm.cashRoi/maxAbsRoi+1)/2,0,1),clamp((hm.todayPnlPct/maxAbsToday+1)/2,0,1),clamp(hm.costYield/maxYield,0,1),clamp(weight/100,0,1),clamp(Number(q?.volume??0)/maxVol,0,1)];const labels=['即時報酬','今日動能','配息','權重','成交量'];const cx=W/2,cy=h/2+4,r=Math.min(84,h*.36),n=vals.length;const pt=(i:number,ratio=1)=>({x:cx+Math.cos(-Math.PI/2+i*Math.PI*2/n)*r*ratio,y:cy+Math.sin(-Math.PI/2+i*Math.PI*2/n)*r*ratio});const data=vals.map((v,i)=>pt(i,v));return <Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`}>{[.25,.5,.75,1].map(rr=><Polygon key={rr} points={vals.map((_,i)=>{const p=pt(i,rr);return `${p.x},${p.y}`}).join(' ')} fill="none" stroke="rgba(255,255,255,.12)"/>)}{vals.map((_,i)=>{const p=pt(i);return <Line key={i} x1={cx} y1={cy} x2={p.x} y2={p.y} stroke="rgba(255,255,255,.10)"/>})}<Polygon points={data.map(p=>`${p.x},${p.y}`).join(' ')} fill={alpha(colors.primary,.2)} stroke={colors.primary} strokeWidth={cfg.lineWidth??2.5}/>{cfg.showLabels!==false?labels.map((l,i)=>{const p=pt(i,1.15);return <SvgText key={l} x={p.x} y={p.y} textAnchor="middle" fill="rgba(255,255,255,.62)" fontSize="8">{l}</SvgText>}):null}</Svg>}
function ScatterHoldings({c,cfg,prefs,h}:{c:Context;cfg:V3ChartConfig;prefs:V3Preferences;h:number}){const colors=palette(prefs,cfg);const total=c.holdings.reduce((s,x)=>s+Number(c.quotes[x.symbol]?.price??x.fallbackPrice??0)*x.shares,0);const rows=c.holdings.map(x=>{const hm=calculateHoldingView(x,c.quotes as any,c.ledger,c.dividends);return {symbol:x.symbol,x:total>0?hm.marketValue/total*100:0,y:hm.cashRoi}});if(rows.length<2)return noData('散佈圖需要多檔 ETF','至少 2 檔持倉才能比較權重與即時報酬率。',h);const p=30,maxX=Math.max(1,...rows.map(x=>x.x)),minY=Math.min(0,...rows.map(x=>x.y)),maxY=Math.max(0,...rows.map(x=>x.y)),spanY=Math.max(1,maxY-minY);return <Svg width="100%" height={h} viewBox={`0 0 ${W} ${h}`}><Grid h={h} p={p} show={cfg.showGrid!==false}/>{rows.map((r,i)=>{const x=p+r.x/maxX*(W-p*2),y=h-p-(r.y-minY)/spanY*(h-p*2),col=r.y>=0?colors.positive:colors.negative;return <React.Fragment key={r.symbol}><Circle cx={x} cy={y} r={5} fill={col}/>{cfg.showLabels!==false?<SvgText x={x+7} y={y+3} fill="rgba(255,255,255,.65)" fontSize="8">{r.symbol}</SvgText>:null}</React.Fragment>})}<SvgText x={W/2} y={h-4} textAnchor="middle" fill="rgba(255,255,255,.38)" fontSize="8">持倉權重 % →</SvgText></Svg>}

function ChartEngine2Base({config,prefs,context,height=122}:{config:V3ChartConfig;prefs:V3Preferences;context:Context;height?:number}){const type=config.chartType??'line';const points=useMemo(()=>singleSeries(config,context),[config.source,config.metric,config.range,context.dailySnapshots,context.intradayPnlPoints]);const symbol=context.activeSymbol||context.holdings[0]?.symbol;const [history,setHistory]=useState<TwseOhlcvPoint[]>([]);const [historyLoading,setHistoryLoading]=useState(false);useEffect(()=>{let active=true;if((type!=='candlestick'&&type!=='volume')||!symbol){setHistory([]);return()=>{active=false}}setHistoryLoading(true);fetchTwseOhlcvHistory(symbol,Math.max(30,Math.min(120,config.range||60))).then(rows=>{if(active)setHistory(rows)}).catch(()=>{if(active)setHistory([])}).finally(()=>{if(active)setHistoryLoading(false)});return()=>{active=false}},[type,symbol,config.range]);if((type==='candlestick'||type==='volume')&&historyLoading&&!history.length)return noData('載入 TWSE 歷史圖表','正在取得官方 STOCK_DAY OHLC / 成交量資料。',height);switch(type){case'line':return <XY points={points} h={height} cfg={config} prefs={prefs} kind="line"/>;case'area':return <XY points={points} h={height} cfg={config} prefs={prefs} kind="area"/>;case'bar':return <XY points={points} h={height} cfg={config} prefs={prefs} kind="bar"/>;case'positiveBar':return <XY points={points} h={height} cfg={config} prefs={prefs} kind="positiveBar"/>;case'pnlTrend':return <XY points={points} h={height} cfg={config} prefs={prefs} kind="pnlTrend"/>;case'pie':return <Composition c={context} cfg={config} prefs={prefs} h={height}/>;case'donut':return <Composition c={context} cfg={config} prefs={prefs} h={height} donut/>;case'multiLine':return <MultiLine c={context} cfg={config} prefs={prefs} h={height}/>;case'stackedBar':return <Stacked c={context} cfg={config} prefs={prefs} h={height}/>;case'candlestick':return <Candle c={context} cfg={config} prefs={prefs} h={height} history={history}/>;case'volume':return <Volume c={context} cfg={config} prefs={prefs} h={height} history={history}/>;case'heatmap':return <Heatmap c={context} cfg={config} prefs={prefs} h={height}/>;case'waterfall':return <Waterfall c={context} cfg={config} prefs={prefs} h={height}/>;case'progress':return <Progress c={context} cfg={config} prefs={prefs} h={height}/>;case'radar':return <Radar c={context} cfg={config} prefs={prefs} h={height}/>;case'scatter':return <ScatterHoldings c={context} cfg={config} prefs={prefs} h={height}/>;default:return <XY points={points} h={height} cfg={config} prefs={prefs} kind="line"/>;}}


const SAFE_CYCLE:V3ChartConfig['chartType'][]=['line','area','bar','positiveBar','pnlTrend'];
const chartTypeName=(t:V3ChartConfig['chartType'])=>({line:'折線',area:'面積',bar:'柱狀',positiveBar:'損益柱狀',multiLine:'多折線',pie:'圓餅',donut:'環形',stackedBar:'堆疊柱狀',candlestick:'K 線',volume:'成交量',pnlTrend:'損益趨勢',progress:'目標進度',heatmap:'熱力圖',waterfall:'瀑布',radar:'雷達',scatter:'散佈'} as any)[t??'line']??String(t??'line');
const metricName=(m:string)=>({todayPnl:'今日損益',totalPnl:'總損益',totalAssets:'總資產',marketValue:'持股市值',cumulativeDividend:'累積配息'} as any)[m]??m;
const rangeCount=(source:V3ChartConfig['source'],key:V3Preferences['chartInteraction']['defaultRange'])=>source==='intraday'?({ '1d':720,'1w':720,'1m':720,'3m':720,'1y':720,'all':720} as const)[key]:({ '1d':2,'1w':7,'1m':30,'3m':90,'1y':365,'all':3650} as const)[key];

export default function ChartEngine2({config,prefs,context,height=122}:{config:V3ChartConfig;prefs:V3Preferences;context:Context;height?:number}){
 const [localType,setLocalType]=useState<V3ChartConfig['chartType']>(config.chartType??'line');const [open,setOpen]=useState(false);const [zoom,setZoom]=useState(1);const [range,setRange]=useState<V3Preferences['chartInteraction']['defaultRange']>(prefs.chartInteraction?.defaultRange??'1m');const [selected,setSelected]=useState<Point|null>(null);const lastTap=useRef(0);const tapTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const pinch=useRef<{d:number;z:number}|null>(null);const {width}=useWindowDimensions();
 useEffect(()=>setLocalType(config.chartType??'line'),[config.chartType]);
 const rememberKey=`@etf-finance-manager/chart-last:${config.source}:${config.metric}:${context.activeSymbol??'portfolio'}`;
 useEffect(()=>{let alive=true;if(prefs.chartInteraction?.rememberStyle!==false)AsyncStorage.getItem(rememberKey).then(v=>{if(alive&&v&&SAFE_CYCLE.includes(v as any))setLocalType(v as any)}).catch(()=>{});return()=>{alive=false}},[rememberKey,prefs.chartInteraction?.rememberStyle]);
 useEffect(()=>()=>{if(tapTimer.current)clearTimeout(tapTimer.current)},[]);
 const activeConfig={...config,chartType:localType};const detailConfig={...activeConfig,range:rangeCount(config.source,range)};const detailPoints=useMemo(()=>singleSeries(detailConfig,context),[detailConfig.source,detailConfig.metric,detailConfig.range,context.dailySnapshots,context.intradayPnlPoints]);
 const cycle=()=>{const cur=SAFE_CYCLE.indexOf(localType);const next=SAFE_CYCLE[(cur<0?0:cur+1)%SAFE_CYCLE.length];setLocalType(next);if(prefs.chartInteraction?.rememberStyle!==false)void AsyncStorage.setItem(rememberKey,String(next)).catch(()=>{});};
 const handleTap=()=>{const now=Date.now();if(prefs.chartInteraction?.doubleTapZoom!==false&&now-lastTap.current<320){lastTap.current=0;setOpen(true);return}lastTap.current=now;if(prefs.chartInteraction?.singleTapCycle!==false)cycle();};
 const selectAt=(x:number,w:number)=>{if(!detailPoints.length)return;const idx=Math.max(0,Math.min(detailPoints.length-1,Math.round((x/Math.max(1,w))*(detailPoints.length-1))));setSelected(detailPoints[idx])};
 const dist=(touches:any[])=>{if(touches.length<2)return 0;const dx=touches[0].pageX-touches[1].pageX,dy=touches[0].pageY-touches[1].pageY;return Math.sqrt(dx*dx+dy*dy)};
 const hintNode=rendererNode(prefs.editorNodes,'chart:hint','單擊切換 · 長按/雙擊放大');const hintColor=resolveRendererColor(hintNode.textColorMode,hintNode.textColor,'rgba(255,255,255,.4)',0,prefs.positiveColor,prefs.negativeColor,prefs.secondaryTextColor);return <><Pressable accessibilityLabel={`互動圖表，${hintNode.displayName}。目前 ${chartTypeName(localType)}`} onPress={handleTap} onLongPress={()=>setOpen(true)} delayLongPress={420}><View><ChartEngine2Base config={activeConfig} prefs={prefs} context={context} height={height}/>{hintNode.visible?<View pointerEvents="none" style={st.chartHint}><Text style={[st.chartHintText,{color:hintColor}]}>{hintNode.displayName}：{chartTypeName(localType)}</Text></View>:null}</View></Pressable>
 <Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={st.modalBackdrop}><View style={st.chartModal}><View style={st.modalHead}><View style={{flex:1}}><Text style={st.modalTitle}>{metricName(config.metric)}｜{chartTypeName(localType)}</Text><Text style={st.modalSub}>點資料點看數值 · 雙指或 ± 縮放 · 左右拖曳查看</Text></View><TouchableOpacity style={st.closeBtn} onPress={()=>setOpen(false)}><Text style={st.closeText}>離開</Text></TouchableOpacity></View><View style={st.rangeRow}>{(['1d','1w','1m','3m','1y','all'] as const).map(r=><TouchableOpacity key={r} onPress={()=>{setRange(r);setSelected(null)}} style={[st.rangeBtn,range===r&&{borderColor:prefs.accentColor}]}><Text style={[st.rangeText,range===r&&{color:prefs.accentColor}]}>{r==='1d'?'1日':r==='1w'?'1週':r==='1m'?'1月':r==='3m'?'3月':r==='1y'?'1年':'全部'}</Text></TouchableOpacity>)}</View><View style={st.zoomRow}><TouchableOpacity style={st.zoomBtn} onPress={()=>setZoom(z=>Math.max(1,Math.round((z-.25)*100)/100))}><Text style={st.zoomText}>−</Text></TouchableOpacity><Text style={st.zoomLabel}>{Math.round(zoom*100)}%</Text><TouchableOpacity style={st.zoomBtn} onPress={()=>setZoom(z=>Math.min(3,Math.round((z+.25)*100)/100))}><Text style={st.zoomText}>＋</Text></TouchableOpacity></View><ScrollView horizontal showsHorizontalScrollIndicator><Pressable onPress={e=>selectAt(e.nativeEvent.locationX,Math.max(width-36,340)*zoom)} onTouchStart={e=>{const d=dist(e.nativeEvent.touches as any);pinch.current=d?{d,z:zoom}:null}} onTouchMove={e=>{const d=dist(e.nativeEvent.touches as any);if(pinch.current&&d){setZoom(Math.max(1,Math.min(3,pinch.current.z*d/pinch.current.d)))}}} onTouchEnd={()=>{pinch.current=null}}><View style={{width:Math.max(width-36,340)*zoom,paddingVertical:6}}><ChartEngine2Base config={detailConfig} prefs={prefs} context={context} height={Math.max(280,height*1.8)}/></View></Pressable></ScrollView>{selected?<View style={[st.detailCard,{borderColor:alpha(prefs.accentColor,.45)}]}><Text style={st.detailTitle}>{selected.label||'資料點'}</Text><Text style={st.detailValue}>{metricName(config.metric)}　{Number(selected.value).toLocaleString('zh-TW',{maximumFractionDigits:4})}</Text><Text style={st.modalSub}>樣式切換只改顯示方式，不改原始資料與計算結果。</Text></View>:<Text style={st.modalSub}>點擊放大圖表中的資料點，即可固定顯示該點資訊。</Text>}</View></View></Modal></>;
}

const st=StyleSheet.create({noData:{alignItems:'center',justifyContent:'center',padding:12,borderRadius:10,borderWidth:1,borderColor:'rgba(255,255,255,.07)',backgroundColor:'rgba(255,255,255,.025)'},noDataTitle:{color:'rgba(255,255,255,.82)',fontSize:11,fontWeight:'900'},noDataText:{color:'rgba(255,255,255,.48)',fontSize:9,textAlign:'center',lineHeight:14,marginTop:5},legendRow:{position:'absolute',left:8,right:8,bottom:2,flexDirection:'row',justifyContent:'center',gap:8},legend:{color:'rgba(255,255,255,.58)',fontSize:8,fontWeight:'700'},progressTrack:{height:18,borderRadius:9,overflow:'hidden',backgroundColor:'rgba(255,255,255,.10)'},progressFill:{height:'100%',borderRadius:9},progressText:{color:'rgba(255,255,255,.75)',fontSize:10,fontWeight:'800',textAlign:'center',marginTop:8},chartHint:{position:'absolute',right:4,bottom:2,backgroundColor:'rgba(0,0,0,.35)',borderRadius:6,paddingHorizontal:5,paddingVertical:2},chartHintText:{fontSize:7,color:'rgba(255,255,255,.4)'},modalBackdrop:{flex:1,backgroundColor:'rgba(0,0,0,.78)',justifyContent:'center',padding:10},chartModal:{maxHeight:'92%',backgroundColor:'#0c1626',borderRadius:16,borderWidth:1,borderColor:'rgba(255,255,255,.14)',padding:12},modalHead:{flexDirection:'row',gap:10,alignItems:'center',marginBottom:8},modalTitle:{color:'#fff',fontSize:17,fontWeight:'900'},modalSub:{color:'rgba(255,255,255,.5)',fontSize:9,marginTop:3},closeBtn:{minHeight:38,paddingHorizontal:13,borderRadius:9,borderWidth:1,borderColor:'rgba(255,255,255,.18)',alignItems:'center',justifyContent:'center'},closeText:{color:'#fff',fontWeight:'900'},rangeRow:{flexDirection:'row',flexWrap:'wrap',gap:5,marginBottom:7},rangeBtn:{borderWidth:1,borderColor:'rgba(255,255,255,.12)',borderRadius:8,paddingHorizontal:9,paddingVertical:6},rangeText:{color:'rgba(255,255,255,.62)',fontSize:9,fontWeight:'800'},zoomRow:{flexDirection:'row',alignItems:'center',justifyContent:'flex-end',gap:8,marginBottom:4},zoomBtn:{width:34,height:30,borderRadius:8,borderWidth:1,borderColor:'rgba(255,255,255,.15)',alignItems:'center',justifyContent:'center'},zoomText:{color:'#fff',fontSize:17,fontWeight:'900'},zoomLabel:{color:'rgba(255,255,255,.68)',fontSize:10,minWidth:44,textAlign:'center'},detailCard:{marginTop:8,padding:10,borderWidth:1,borderRadius:10,backgroundColor:'rgba(255,255,255,.035)'},detailTitle:{color:'rgba(255,255,255,.58)',fontSize:10,fontWeight:'800'},detailValue:{color:'#fff',fontSize:15,fontWeight:'900',marginTop:3,fontVariant:['tabular-nums']}});
