import React,{useEffect,useMemo,useState} from 'react';
import {Modal,ScrollView,StyleSheet,Switch,Text,TouchableOpacity,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import ColorPalettePicker from '../components/ColorPalettePicker';
import type {MonitorField,MonitorFieldStyle} from './monitoring';

const LABELS:Record<MonitorField,string>={symbol:'ETF代號',name:'名稱',price:'即時行情',nav:'NAV',premium:'折溢價',change:'漲跌',changePct:'漲跌幅',shares:'持有股數',marketValue:'即時市值',pureCost:'純成本',instantPnl:'庫存即時損益',instantRoi:'庫存報酬率',todayPnl:'今日損益',todayPnlPct:'今日損益率',previousClose:'昨收',open:'開盤',high:'最高',low:'最低',volume:'成交量',updatedAt:'更新時間',totalAssets:'總資產',dividend:'股息'};
const PNL=new Set<MonitorField>(['price','premium','change','changePct','instantPnl','instantRoi','todayPnl','todayPnlPct']);
const base=(order=1,field?:MonitorField|null):MonitorFieldStyle=>({visible:true,order,fixed:false,fontScale:100,fontWeight:'bold',textColor:'#FFFFFF',backgroundColor:'#00000000',backgroundOpacity:0,align:'center',verticalAlign:'center',padding:4,radius:4,effect:'none',effectStrength:35,profitLossColor:true,positiveColor:'#E54A45',negativeColor:'#12A875',neutralColor:field==='price'?'#F4D35E':'#8E9BAE',limitUpTextColor:'#FFFFFF',limitUpBackgroundColor:'#E54A45',limitDownTextColor:'#FFFFFF',limitDownBackgroundColor:'#12A875'});
function Step({value,min,max,step=5,onChange}:{value:number;min:number;max:number;step?:number;onChange:(v:number)=>void}){return <View style={s.step}><TouchableOpacity style={s.stepBtn} onPress={()=>onChange(Math.max(min,value-step))}><Text style={s.stepText}>−</Text></TouchableOpacity><Text style={s.stepValue}>{value}</Text><TouchableOpacity style={s.stepBtn} onPress={()=>onChange(Math.min(max,value+step))}><Text style={s.stepText}>＋</Text></TouchableOpacity></View>}
function Choices({value,items,onChange}:{value:string;items:Array<[string,string]>;onChange:(v:any)=>void}){return <View style={s.row}>{items.map(([k,l])=><TouchableOpacity key={k} style={[s.choice,value===k&&s.choiceOn]} onPress={()=>onChange(k)}><Text style={[s.choiceText,value===k&&s.choiceTextOn]}>{l}</Text></TouchableOpacity>)}</View>}
export default function MonitorFieldEditor({visible,field,style,orderMax,positive,negative,sampleValue,onSave,onClose}:{visible:boolean;field:MonitorField|null;style?:MonitorFieldStyle;orderMax:number;positive:string;negative:string;sampleValue?:string;onSave:(v:MonitorFieldStyle)=>void;onClose:()=>void}){
 const insets=useSafeAreaInsets();const initial=useMemo(()=>{const defaults=base(style?.order??1,field);const legacyFlat=field==='price'&&style?.neutralColor==='#8E9BAE';return {...defaults,...style,positiveColor:style?.positiveColor??positive,negativeColor:style?.negativeColor??negative,neutralColor:legacyFlat?defaults.neutralColor:(style?.neutralColor??defaults.neutralColor),limitUpTextColor:style?.limitUpTextColor??defaults.limitUpTextColor,limitUpBackgroundColor:style?.limitUpBackgroundColor??defaults.limitUpBackgroundColor,limitDownTextColor:style?.limitDownTextColor??defaults.limitDownTextColor,limitDownBackgroundColor:style?.limitDownBackgroundColor??defaults.limitDownBackgroundColor}},[field,style,positive,negative]);const[d,setD]=useState<MonitorFieldStyle>(initial);useEffect(()=>setD(initial),[initial]);if(!field)return null;const pnl=PNL.has(field);const patch=(x:Partial<MonitorFieldStyle>)=>setD(v=>({...v,...x}));
 return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={[s.safe,{paddingTop:Math.max(12,insets.top),paddingBottom:Math.max(12,insets.bottom)}]}><View style={s.head}><View style={{flex:1}}><Text style={s.title}>{LABELS[field]}－個別編輯</Text><Text style={s.sub}>此視窗只編輯目前資料項目；儲存後才正式套用。</Text></View><TouchableOpacity style={s.close} onPress={onClose}><Text style={s.closeText}>✕</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.body}>
 <View style={s.setting}><Text style={s.label}>顯示</Text><Switch value={d.visible!==false} onValueChange={v=>patch({visible:v})}/></View>
 <View style={s.setting}><Text style={s.label}>顯示順序</Text><Step value={d.order} min={1} max={Math.max(1,orderMax)} step={1} onChange={v=>patch({order:v})}/></View>
 <View style={s.setting}><Text style={s.label}>固定此功能項目 📌</Text><Switch value={d.fixed===true} onValueChange={v=>patch({fixed:v})}/></View>
 <View style={s.setting}><Text style={s.label}>字體大小 %</Text><Step value={d.fontScale} min={60} max={220} onChange={v=>patch({fontScale:v})}/></View>
 <View style={s.setting}><Text style={s.label}>字體粗細</Text><Choices value={d.fontWeight} items={[["normal","一般"],["bold","粗體"]]} onChange={v=>patch({fontWeight:v})}/></View>
 <ColorPalettePicker label="文字顏色" value={d.textColor} onChange={v=>patch({textColor:v})}/><ColorPalettePicker label="背景底色" value={d.backgroundColor} onChange={v=>patch({backgroundColor:v})}/>
 <View style={s.setting}><Text style={s.label}>底色透明度 %</Text><Step value={d.backgroundOpacity} min={0} max={100} onChange={v=>patch({backgroundOpacity:v})}/></View>
 {pnl?<><View style={s.setting}><Text style={s.label}>{field==='price'?'市場行情色':'損益色'}</Text><Switch value={d.profitLossColor!==false} onValueChange={v=>patch({profitLossColor:v})}/></View>{d.profitLossColor!==false?<><ColorPalettePicker label="正值 / 上漲色" value={d.positiveColor} onChange={v=>patch({positiveColor:v})}/><ColorPalettePicker label="負值 / 下跌色" value={d.negativeColor} onChange={v=>patch({negativeColor:v})}/><ColorPalettePicker label="持平色" value={d.neutralColor} onChange={v=>patch({neutralColor:v})}/>{field==='price'?<><ColorPalettePicker label="漲停文字顏色" value={d.limitUpTextColor??'#FFFFFF'} onChange={v=>patch({limitUpTextColor:v})}/><ColorPalettePicker label="漲停背景顏色" value={d.limitUpBackgroundColor??'#E54A45'} onChange={v=>patch({limitUpBackgroundColor:v})}/><ColorPalettePicker label="跌停文字顏色" value={d.limitDownTextColor??'#FFFFFF'} onChange={v=>patch({limitDownTextColor:v})}/><ColorPalettePicker label="跌停背景顏色" value={d.limitDownBackgroundColor??'#12A875'} onChange={v=>patch({limitDownBackgroundColor:v})}/></>:null}</>:null}</>:null}
 <View style={s.setting}><Text style={s.label}>水平對齊</Text><Choices value={d.align} items={[["left","靠左"],["center","置中"],["right","靠右"]]} onChange={v=>patch({align:v})}/></View><View style={s.setting}><Text style={s.label}>垂直對齊</Text><Choices value={d.verticalAlign} items={[["top","上"],["center","中"],["bottom","下"]]} onChange={v=>patch({verticalAlign:v})}/></View>
 <View style={s.setting}><Text style={s.label}>內距</Text><Step value={d.padding} min={0} max={30} step={1} onChange={v=>patch({padding:v})}/></View><View style={s.setting}><Text style={s.label}>圓角</Text><Step value={d.radius} min={0} max={30} step={1} onChange={v=>patch({radius:v})}/></View>
 <View style={s.setting}><Text style={s.label}>特效</Text><Choices value={d.effect} items={[["none","無"],["shadow","陰影"],["glow","發光"],["outline","描邊"]]} onChange={v=>patch({effect:v})}/></View>{d.effect!=='none'?<View style={s.setting}><Text style={s.label}>特效強度</Text><Step value={d.effectStrength} min={0} max={100} onChange={v=>patch({effectStrength:v})}/></View>:null}
 <Text style={s.previewTitle}>即時預覽</Text><View style={[s.preview,{borderRadius:d.radius,padding:d.padding,backgroundColor:d.backgroundOpacity?d.backgroundColor:'#FFFFFF'}]}><Text style={{fontSize:Math.max(10,16*d.fontScale/100),fontWeight:d.fontWeight,color:pnl&&d.profitLossColor?d.positiveColor:d.textColor,textAlign:d.align,textShadowColor:d.effect==='none'?'transparent':d.effect==='glow'?(pnl?d.positiveColor:d.textColor):'#000',textShadowRadius:d.effect==='none'?0:Math.max(1,d.effectStrength/12),textShadowOffset:{width:d.effect==='shadow'?2:0,height:d.effect==='shadow'?2:0}}}>{sampleValue??(field==='symbol'?'—':'資料不足')}</Text><Text style={s.previewHint}>{LABELS[field]} · 使用目前 App 真實資料 · 儲存後才正式套用</Text></View>
 </ScrollView><View style={s.footer}><TouchableOpacity style={s.cancel} onPress={()=>setD({...base(d.order,field),positiveColor:positive,negativeColor:negative})}><Text style={s.cancelText}>恢復預設</Text></TouchableOpacity><TouchableOpacity style={s.cancel} onPress={onClose}><Text style={s.cancelText}>取消</Text></TouchableOpacity><TouchableOpacity style={s.save} onPress={()=>onSave(d)}><Text style={s.saveText}>✓ 儲存套用</Text></TouchableOpacity></View></View></Modal>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8FAFC'},head:{flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:16,paddingBottom:12,borderBottomWidth:1,borderBottomColor:'#E2E8F0'},title:{color:'#0F172A',fontSize:20,fontWeight:'900'},sub:{color:'#64748B',fontSize:10,lineHeight:15,marginTop:3},close:{width:40,height:40,borderRadius:20,backgroundColor:'#FFFFFF',alignItems:'center',justifyContent:'center'},closeText:{color:'#0066FF',fontSize:17},body:{padding:16,paddingBottom:130},setting:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#E2E8F0'},label:{color:'#0F172A',fontSize:12,fontWeight:'900',marginBottom:8},row:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{minHeight:36,paddingHorizontal:11,borderRadius:8,borderWidth:1,borderColor:'#E2E8F0',alignItems:'center',justifyContent:'center'},choiceOn:{borderColor:'#0066FF',backgroundColor:'rgba(0,102,255,.13)'},choiceText:{color:'#64748B',fontSize:10,fontWeight:'800'},choiceTextOn:{color:'#0066FF'},step:{flexDirection:'row',alignItems:'center',gap:14},stepBtn:{width:36,height:36,borderRadius:18,backgroundColor:'#EFF6FF',alignItems:'center',justifyContent:'center'},stepText:{color:'#0F172A',fontSize:18,fontWeight:'900'},stepValue:{color:'#0066FF',minWidth:52,textAlign:'center',fontWeight:'900'},previewTitle:{color:'#0066FF',fontSize:14,fontWeight:'900',marginTop:20,marginBottom:8},preview:{minHeight:100,borderWidth:1,borderColor:'#E2E8F0',justifyContent:'center'},previewHint:{color:'#64748B',fontSize:9,marginTop:8},footer:{position:'absolute',left:0,right:0,bottom:0,flexDirection:'row',gap:7,padding:12,backgroundColor:'#FFFFFF',borderTopWidth:1,borderTopColor:'rgba(255,255,255,.09)'},cancel:{flex:1,minHeight:48,borderRadius:12,borderWidth:1,borderColor:'#E2E8F0',alignItems:'center',justifyContent:'center'},cancelText:{color:'#0F172A',fontWeight:'800',fontSize:10},save:{flex:1.5,minHeight:48,borderRadius:12,backgroundColor:'#0066FF',alignItems:'center',justifyContent:'center'},saveText:{color:'#FFFFFF',fontWeight:'900'}});
