import type { FlexAlignType, TextStyle, ViewStyle } from 'react-native';

export type EditableUiKind='page'|'section'|'title'|'subtitle'|'label'|'value'|'card'|'list'|'chart'|'button'|'statusBar'|'floatingWindow'|'widget'|'ai'|'breathingStatus';
export type UniversalColorMode='fixed'|'theme'|'profitLoss'|'auto';
export type EffectKind='profitLoss'|'outline'|'outerGlow'|'innerGlow'|'outerShadow'|'innerShadow'|'gradient'|'glass'|'fade'|'breathe'|'blink'|'alertPulse'|'shimmer'|'sweep'|'scalePulse'|'fadeInOut';
export type EffectDirection='left'|'right'|'up'|'down'|'in'|'out';
export type VisualEffect={id:string;kind:EffectKind;enabled:boolean;order:number;intensity:number;opacity:number;color?:string;speedMs:number;direction:EffectDirection;range:number};
export type EdgeSpacing={top:number;right:number;bottom:number;left:number};
export type UniversalTextStyle={visible:boolean;fontSize:number;fontWeight:TextStyle['fontWeight'];colorMode:UniversalColorMode;color?:string;align:'left'|'center'|'right';verticalAlign:'top'|'center'|'bottom';letterSpacing:number;lineHeight:number;opacity:number;wrap:boolean;margin:EdgeSpacing;padding:EdgeSpacing};
export type UniversalSizeConfig={widthMode:'auto'|'fill'|'ratio'|'fixed';widthRatio:'1'|'3/4'|'2/3'|'1/2'|'1/3'|'1/4';width?:number;height?:number;minHeight:number;maxHeight:number;autoHeight:boolean;radius:number;limits:{minWidth:number;maxWidth:number;aspectRatio?:number;lockAspectRatio:boolean}};
export type UniversalDataConfig={source:'none'|'portfolio'|'holding'|'quote'|'ledger'|'dividend'|'watchlist'|'market'|'ai'|'custom';fieldBinding:string;format:'text'|'number'|'money'|'percent'|'date'|'time'|'custom';decimals:number;percentage:boolean;unit:string;showSign:boolean;profitLossSource:'none'|'value'|'todayPnl'|'totalPnl'|'change'|'changePct'|'custom';profitLossBinding?:string};
export type UniversalInteractionConfig={onPress:'none'|'navigate'|'toggle'|'expand'|'refresh'|'custom';longPress:'none'|'edit'|'custom';doubleTap:'none'|'expand'|'zoom'|'refresh'|'custom';navigationTarget:string;expandable:boolean;expandedByDefault:boolean;draggable:boolean;resizable:boolean};
export type UniversalCapabilityFlags={rename:boolean;visibility:boolean;textStyle:boolean;size:boolean;color:boolean;dataBinding:boolean;interaction:boolean;effects:boolean;refresh:boolean;drag:boolean;resize:boolean};
export type UniversalAdvancedConfig={conditionalVisibility:{enabled:boolean;source:string;operator:'truthy'|'falsy'|'eq'|'neq'|'gt'|'gte'|'lt'|'lte';value:string};statusRules:Array<{id:string;state:string;condition:string;displayName?:string;colorMode:UniversalColorMode;color?:string}>;refresh:{mode:'inherit'|'manual'|'onFocus'|'interval'|'realtime';intervalSeconds:number;updateWhenHidden:boolean};readonly:boolean;systemFixed:boolean;capabilities:UniversalCapabilityFlags};
export type UniversalEditorNode={id:string;kind:EditableUiKind;systemName:string;displayName?:string;text?:UniversalTextStyle;backgroundColorMode?:UniversalColorMode;backgroundColor?:string;borderColorMode?:UniversalColorMode;borderColor?:string;size?:UniversalSizeConfig;data?:UniversalDataConfig;interaction?:UniversalInteractionConfig;advanced?:UniversalAdvancedConfig;effects:VisualEffect[]};
export type ProfitLossPalette={positive:string;negative:string;neutral:string};

export const emptySpacing=():EdgeSpacing=>({top:0,right:0,bottom:0,left:0});
export const defaultTextStyle=():UniversalTextStyle=>({visible:true,fontSize:14,fontWeight:'700',colorMode:'theme',align:'left',verticalAlign:'center',letterSpacing:0,lineHeight:20,opacity:1,wrap:true,margin:emptySpacing(),padding:emptySpacing()});
export const defaultSizeConfig=():UniversalSizeConfig=>({widthMode:'auto',widthRatio:'1',minHeight:0,maxHeight:1200,autoHeight:true,radius:0,limits:{minWidth:0,maxWidth:1200,lockAspectRatio:false}});
export const defaultDataConfig=():UniversalDataConfig=>({source:'none',fieldBinding:'',format:'text',decimals:2,percentage:false,unit:'',showSign:false,profitLossSource:'none'});
export const defaultInteractionConfig=():UniversalInteractionConfig=>({onPress:'none',longPress:'edit',doubleTap:'none',navigationTarget:'',expandable:false,expandedByDefault:false,draggable:false,resizable:false});
export const defaultCapabilityFlags=():UniversalCapabilityFlags=>({rename:true,visibility:true,textStyle:true,size:true,color:true,dataBinding:true,interaction:true,effects:true,refresh:false,drag:false,resize:false});
export const defaultAdvancedConfig=():UniversalAdvancedConfig=>({conditionalVisibility:{enabled:false,source:'',operator:'truthy',value:''},statusRules:[],refresh:{mode:'inherit',intervalSeconds:60,updateWhenHidden:false},readonly:false,systemFixed:false,capabilities:defaultCapabilityFlags()});
export const withUniversalDefaults=(node:UniversalEditorNode):UniversalEditorNode=>({...node,text:{...defaultTextStyle(),...(node.text??{}),margin:{...emptySpacing(),...(node.text?.margin??{})},padding:{...emptySpacing(),...(node.text?.padding??{})}},size:{...defaultSizeConfig(),...(node.size??{}),limits:{...defaultSizeConfig().limits,...(node.size?.limits??{})}},data:{...defaultDataConfig(),...(node.data??{})},interaction:{...defaultInteractionConfig(),...(node.interaction??{})},advanced:{...defaultAdvancedConfig(),...(node.advanced??{}),conditionalVisibility:{...defaultAdvancedConfig().conditionalVisibility,...(node.advanced?.conditionalVisibility??{})},refresh:{...defaultAdvancedConfig().refresh,...(node.advanced?.refresh??{})},capabilities:{...defaultCapabilityFlags(),...(node.advanced?.capabilities??{})},statusRules:Array.isArray(node.advanced?.statusRules)?node.advanced.statusRules:[]},effects:Array.isArray(node.effects)?node.effects:[]});
export const EFFECT_KINDS:EffectKind[]=['profitLoss','outline','outerGlow','innerGlow','outerShadow','innerShadow','gradient','glass','fade','breathe','blink','alertPulse','shimmer','sweep','scalePulse','fadeInOut'];
export const effectDefaults=(kind:EffectKind,order=0):VisualEffect=>({id:`${kind}-${Date.now()}-${order}`,kind,enabled:true,order,intensity:40,opacity:1,speedMs:1800,direction:'right',range:12});
export const displayNameOf=(node:Pick<UniversalEditorNode,'displayName'|'systemName'>)=>node.displayName?.trim()||node.systemName;
export function resolveColor(mode:UniversalColorMode,fixed:string|undefined,theme:string,pnl:number|undefined,palette:ProfitLossPalette){if(mode==='fixed'&&fixed)return fixed;if(mode==='profitLoss'&&Number.isFinite(pnl))return Number(pnl)>0?palette.positive:Number(pnl)<0?palette.negative:palette.neutral;if(mode==='auto'&&fixed)return fixed;return theme}
export function textStyleFor(config:UniversalTextStyle,color:string):TextStyle{return {display:config.visible?'flex':'none',fontSize:config.fontSize,fontWeight:config.fontWeight,color,textAlign:config.align,letterSpacing:config.letterSpacing,lineHeight:config.lineHeight,opacity:config.opacity,flexWrap:config.wrap?'wrap':'nowrap',marginTop:config.margin.top,marginRight:config.margin.right,marginBottom:config.margin.bottom,marginLeft:config.margin.left,paddingTop:config.padding.top,paddingRight:config.padding.right,paddingBottom:config.padding.bottom,paddingLeft:config.padding.left,textAlignVertical:config.verticalAlign}}
export function effectsStyle(effects:VisualEffect[],fallback='#000'):ViewStyle{const active=effects.filter(x=>x.enabled).sort((a,b)=>a.order-b.order);const shadow=active.find(x=>x.kind==='outerShadow'||x.kind==='outerGlow');const outline=active.find(x=>x.kind==='outline');const glass=active.find(x=>x.kind==='glass');return {borderWidth:outline?Math.max(1,outline.range/5):undefined,borderColor:outline?.color??fallback,shadowColor:shadow?.color??fallback,shadowOpacity:shadow?shadow.opacity:0,shadowRadius:shadow?Math.max(1,shadow.range):0,shadowOffset:{width:0,height:shadow?.kind==='outerShadow'?Math.max(1,shadow.range/3):0},elevation:shadow?Math.ceil(shadow.intensity/20):0,opacity:glass?Math.max(.2,glass.opacity):1}}
export const alignItemsFor=(align:UniversalTextStyle['align']):FlexAlignType=>align==='left'?'flex-start':align==='right'?'flex-end':'center';
