import {defaultTextStyle,withUniversalDefaults,type EditableUiKind,type UniversalEditorNode,type UniversalColorMode,type VisualEffect} from './editorSchema';

export type RegisteredUiNode={id:string;kind:EditableUiKind;systemName:string;renderer:'react'|'chart'|'widget'|'overlay'|'legacy';editable:boolean};
const editable=(id:string,kind:EditableUiKind,systemName:string,renderer:RegisteredUiNode['renderer']):RegisteredUiNode=>({id,kind,systemName,renderer,editable:true});
export const UNIVERSAL_UI_REGISTRY:RegisteredUiNode[]=[
 editable('chart:axis:x','label','X 軸標籤','chart'),editable('chart:axis:y','label','Y 軸標籤','chart'),editable('chart:legend:title','label','圖例','chart'),editable('chart:empty:title','label','圖表資料不足','chart'),editable('chart:hint','label','單擊切換 · 長按/雙擊放大','chart'),
 editable('widget:root:title','widget','ETF財務管家','widget'),editable('widget:market:live','statusBar','盤中 / 最新快照','widget'),editable('widget:market:closed','statusBar','盤後快照','widget'),editable('widget:pnl:label','label','累積總損益','widget'),editable('widget:pnl:single','label','即時損益','widget'),editable('widget:updatedAt:label','label','更新時間','widget'),
 editable('overlay:root:title','floatingWindow','即時監控器','overlay'),editable('overlay:status:title','breathingStatus','市場狀態','overlay'),editable('overlay:summary:cost','label','總成本','overlay'),editable('overlay:summary:value','label','總市值','overlay'),editable('overlay:summary:pnl','label','損益','overlay'),editable('overlay:footer:unlocked','label','可拖移/縮放','overlay'),
 ...['symbol:ETF代號','name:名稱','price:即時行情','change:漲跌','changePct:漲跌幅','shares:持有股數','marketValue:即時市值','pureCost:純成本','instantPnl:庫存即時損益','instantRoi:庫存報酬率','todayPnl:今日損益','todayPnlPct:今日損益率','previousClose:昨收','open:開盤','high:最高','low:最低','volume:成交量','nav:NAV','premium:折溢價','updatedAt:更新'].map(x=>{const [key,...label]=x.split(':');return editable(`overlay:field:${key}`,'label',label.join(':'),'overlay')}),
 ...['home:首頁','portfolio:庫存','dailyProfit:每日損益','dividend:股息日','goal:目標中心','scenario:情境實驗室','data:資料管理','addHolding:新增持倉','editHolding:編輯持倉'].map(x=>{const [key,label]=x.split(':');return editable(`legacy:${key}:title`,'title',label,'legacy')})
];
export const defaultRegisteredNodes=():Record<string,UniversalEditorNode>=>Object.fromEntries(UNIVERSAL_UI_REGISTRY.map(r=>[r.id,withUniversalDefaults({id:r.id,kind:r.kind,systemName:r.systemName,text:defaultTextStyle(),backgroundColorMode:'theme',borderColorMode:'theme',effects:[]})])) as Record<string,UniversalEditorNode>;
export type RendererNode={displayName:string;visible:boolean;textColorMode:UniversalColorMode;textColor?:string;backgroundColorMode:UniversalColorMode;backgroundColor?:string;borderColorMode:UniversalColorMode;borderColor?:string;effects:VisualEffect[]};
export function rendererNode(nodes:Record<string,UniversalEditorNode>|undefined,id:string,fallback:string):RendererNode{const node=nodes?.[id];return {displayName:node?.displayName?.trim()||node?.systemName||fallback,visible:node?.text?.visible!==false,textColorMode:node?.text?.colorMode??'theme',textColor:node?.text?.color,backgroundColorMode:node?.backgroundColorMode??'theme',backgroundColor:node?.backgroundColor,borderColorMode:node?.borderColorMode??'theme',borderColor:node?.borderColor,effects:(node?.effects??[]).filter(x=>x.enabled).sort((a,b)=>a.order-b.order)}}
export function resolveRendererColor(mode:UniversalColorMode,fixed:string|undefined,theme:string,pnl:number,positive:string,negative:string,neutral:string){if(mode==='fixed'&&fixed)return fixed;if(mode==='profitLoss')return pnl>0?positive:pnl<0?negative:neutral;if(mode==='auto')return fixed||theme;return theme}
