import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, View, Pressable } from 'react-native';
import { ScaledText as Text } from '../components/ScaledText';
import Svg, { Polyline, Circle, Line } from 'react-native-svg';
import { DailySnapshot, LayoutSettings } from '../storage/appStorage';
import { Card, Header, palette, SectionTitle } from '../components/Ui';
import { money } from '../v3/engine';
const signedMoney=(n:number)=>`${Number(n)>=0?'+':'-'}${money(Math.abs(Number(n)||0))}`;
const signedPercent=(n:number)=>`${Number(n)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
import { PageLayoutEditor } from '../components/PageLayoutEditor';

type MetricKey='totalPnl'|'todayPnl'|'costPnl'|'marketValue'|'cumulativeDividend';
const labels:Record<MetricKey,string>={totalPnl:'含息總損益',todayPnl:'今日損益',costPnl:'成本損益',marketValue:'總資產',cumulativeDividend:'累積配息'};
const DAILY_CHOICES=[{key:'todayPnl',label:'今日損益',category:'損益'},{key:'todayPnlPct',label:'今日損益 %',category:'損益'},{key:'costPnl',label:'成本損益',category:'損益'},{key:'costPnlPct',label:'成本損益 %',category:'損益'},{key:'totalPnl',label:'含息總損益',category:'損益'},{key:'totalPnlPct',label:'含息總損益 %',category:'損益'},{key:'marketValue',label:'總資產',category:'資產'},{key:'totalCost',label:'持有總成本',category:'資產'},{key:'cumulativeDividend',label:'累積配息',category:'配息'},{key:'date',label:'快照日期',category:'日期'},{key:'chart',label:'走勢圖',category:'圖表'},{key:'etfDetail',label:'各 ETF 當日明細',category:'明細'}];
export default function DailyProfitScreen({snapshots,layout,onLayoutChange}:{snapshots:DailySnapshot[];layout:LayoutSettings;onLayoutChange:(p:Partial<LayoutSettings>)=>void}){
 const [layoutOpen,setLayoutOpen]=useState(false); const page=layout.pageLayouts.dailyProfit??{fields:DAILY_CHOICES.map(x=>x.key),spans:{todayPnl:3,todayPnlPct:3,costPnl:3,costPnlPct:3,totalPnl:3,totalPnlPct:3,marketValue:3,totalCost:3,cumulativeDividend:3,date:3,chart:6,etfDetail:6}};
 const [metric,setMetric]=useState<MetricKey>('totalPnl'); const [range,setRange]=useState(30); const [selected,setSelected]=useState<DailySnapshot|undefined>(()=>snapshots[snapshots.length-1]); const rows=useMemo(()=>snapshots.slice(Math.max(0,snapshots.length-range)),[snapshots,range]);
 const value=(s:DailySnapshot,k:string):[string,string,string?]=>{const m:any={todayPnl:['今日損益',signedMoney(s.todayPnl),signedPercent(s.todayPnlPct)],todayPnlPct:['今日損益 %',signedPercent(s.todayPnlPct)],costPnl:['成本損益',signedMoney(s.costPnl),signedPercent(s.costPnlPct)],costPnlPct:['成本損益 %',signedPercent(s.costPnlPct)],totalPnl:['含息總損益',signedMoney(s.totalPnl),signedPercent(s.totalPnlPct)],totalPnlPct:['含息總損益 %',signedPercent(s.totalPnlPct)],marketValue:['總資產',money(s.marketValue)],totalCost:['持有總成本',money(s.totalCost)],cumulativeDividend:['累積配息',money(s.cumulativeDividend)],date:['快照日期',s.date]};return m[k]??[k,'—']};
 return <ScrollView contentContainerStyle={styles.content}><Header title="每日損益" subtitle="收盤快照與走勢紀錄" slogan="每天留下一筆，長期看見資產變化。" onLayoutPress={()=>setLayoutOpen(true)}/><PageLayoutEditor visible={layoutOpen} title="每日損益排版設定" choices={DAILY_CHOICES} selected={page.fields} spans={page.spans} onClose={()=>setLayoutOpen(false)} onSave={(fields,spans)=>onLayoutChange({pageLayouts:{...layout.pageLayouts,dailyProfit:{fields,spans}}})}/>
  {page.fields.includes('chart')?<Card><SectionTitle title="走勢圖" subtitle="點選指標與日期查看明細"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{(Object.keys(labels) as MetricKey[]).map(k=><Pressable key={k} onPress={()=>setMetric(k)} style={[styles.chip,metric===k&&styles.chipOn]}><Text style={[styles.chipText,metric===k&&styles.chipTextOn]}>{labels[k]}</Text></Pressable>)}</ScrollView><Trend rows={rows} metric={metric} onSelect={setSelected}/><View style={styles.range}>{[7,30,90,180,365].map(v=><Pressable key={v} onPress={()=>setRange(v)} style={[styles.rangeBtn,range===v&&styles.rangeOn]}><Text style={styles.rangeText}>{v===30?'1月':v===90?'3月':v===180?'6月':v===365?'1年':'7日'}</Text></Pressable>)}</View></Card>:null}
  {selected?<Card><SectionTitle title={selected.date} subtitle="當日收盤快照"/><View style={styles.grid}>{page.fields.filter(k=>!['chart','etfDetail'].includes(k)).map(k=>{const a=value(selected,k);const n=(page.spans[k]||6);return <View key={k} style={[styles.box,{width:n===6?'100%':n===3?'49%':'32%'}]}><Text style={styles.label}>{a[0]}</Text><Text style={styles.val}>{a[1]}</Text>{a[2]?<Text style={styles.sub}>{a[2]}</Text>:null}</View>})}</View>{page.fields.includes('etfDetail')?<><Text style={styles.tableTitle}>各 ETF 當日明細（可左右滑動）</Text><ScrollView horizontal showsHorizontalScrollIndicator><View style={styles.table}>{selected.holdings.map(h=><View key={h.symbol} style={styles.tr}><Text style={styles.symbol}>{h.symbol}</Text><Text style={styles.cell}>{h.shares.toLocaleString()} 股</Text><Text style={styles.cell}>行情 {h.price.toFixed(2)}</Text><Text style={styles.cell}>市值 {money(h.marketValue)}</Text><Text style={styles.cell}>今日 {signedMoney(h.todayPnl)}</Text><Text style={styles.cell}>總 {signedMoney(h.totalPnl)}</Text></View>)}</View></ScrollView></>:null}</Card>:<Card><Text style={styles.empty}>尚未建立每日收盤快照。</Text></Card>}
 </ScrollView>;
}
function Trend({rows,metric,onSelect}:{rows:DailySnapshot[];metric:MetricKey;onSelect:(s:DailySnapshot)=>void}){const w=720,h=170,pad=16;if(rows.length<2)return <Text style={styles.empty}>需要至少 2 筆快照才可畫線。</Text>;const vals=rows.map(r=>Number((r as any)[metric]??0));const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min);const pts=rows.map((r,i)=>({x:pad+i*(w-pad*2)/(rows.length-1),y:h-pad-(vals[i]-min)/span*(h-pad*2),r}));return <ScrollView horizontal showsHorizontalScrollIndicator><Pressable><Svg width={w} height={h}><Line x1={pad} y1={h-pad} x2={w-pad} y2={h-pad} stroke="#DDE4E1"/><Polyline points={pts.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#14835E" strokeWidth="3"/>{pts.map((p,i)=><Circle key={i} cx={p.x} cy={p.y} r="6" fill="#14835E" onPress={()=>onSelect(p.r)}/>)}</Svg></Pressable></ScrollView>}
const styles=StyleSheet.create({content:{paddingBottom:98},chips:{gap:6,paddingBottom:8},chip:{paddingHorizontal:10,minHeight:34,borderRadius:17,borderWidth:1,borderColor:palette.line,justifyContent:'center'},chipOn:{backgroundColor:palette.greenSoft,borderColor:palette.green},chipText:{fontSize:9,fontWeight:'800',color:palette.text},chipTextOn:{color:palette.green},range:{flexDirection:'row',gap:6,marginTop:8},rangeBtn:{flex:1,minHeight:32,borderRadius:9,backgroundColor:palette.surfaceSoft,alignItems:'center',justifyContent:'center'},rangeOn:{backgroundColor:palette.greenSoft},rangeText:{fontSize:9,fontWeight:'800',color:palette.text},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:8},box:{borderWidth:1,borderColor:palette.line,borderRadius:10,padding:9,backgroundColor:palette.surfaceSoft,minHeight:65},label:{fontSize:9,color:palette.muted},val:{fontSize:13,fontWeight:'900',color:palette.text,textAlign:'right',marginTop:5},sub:{fontSize:8.5,color:palette.muted,textAlign:'right',marginTop:2},tableTitle:{fontSize:11,fontWeight:'900',color:palette.text,marginTop:14},table:{minWidth:760},tr:{flexDirection:'row',gap:12,paddingVertical:9,borderBottomWidth:1,borderColor:palette.line},symbol:{width:60,color:palette.blue,fontWeight:'900'},cell:{width:120,fontSize:9,color:palette.text},empty:{color:palette.muted,fontSize:11,paddingVertical:20}});
