import React, { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { ScaledText as Text } from '../components/ScaledText';
import { Holding } from '../data/portfolio';
import { Card, Header, palette, SectionTitle } from '../components/Ui';
import DatePickerField from '../components/DatePickerField';
import { LayoutSettings } from '../storage/appStorage';
import { PageLayoutEditor } from '../components/PageLayoutEditor';
export type DividendEvent={id:string;symbol:string;name:string;announcementDate?:string;lastBuyDate:string;exDate:string;payDate:string;dividend:string;note:string;eligibleShares?:number;estimatedAmount?:number;actualAmount?:number;status?:'planned'|'exDatePassed'|'pending'|'paid';reminder?:boolean;source?:string;paidAt?:string;fillStatus?:'unknown'|'filled'|'unfilled';fillDate?:string};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const DIV_CHOICES=[{key:'symbol',label:'ETF 代號',category:'ETF'},{key:'name',label:'ETF 名稱',category:'ETF'},{key:'lastBuyDate',label:'最後買進日',category:'日期'},{key:'exDate',label:'除息日',category:'日期'},{key:'payDate',label:'股息發放日',category:'日期'},{key:'dividend',label:'每股配息',category:'配息'},{key:'eligibleShares',label:'符合資格股數',category:'配息'},{key:'estimatedDividend',label:'預估配息',category:'配息'},{key:'actualDividend',label:'實際領息',category:'配息'},{key:'status',label:'配息狀態',category:'狀態'},{key:'reminder',label:'提醒狀態',category:'狀態'},{key:'source',label:'資料來源',category:'其他'},{key:'note',label:'備註',category:'其他'},{key:'calendar',label:'月曆事件清單',category:'區塊'},{key:'editor',label:'新增 / 修改表單',category:'區塊'}];
export default function DividendCalendarScreen({holdings,events,setEvents,layout,onLayoutChange}:{holdings:Holding[];events:DividendEvent[];setEvents:React.Dispatch<React.SetStateAction<DividendEvent[]>>;layout:LayoutSettings;onLayoutChange:(p:Partial<LayoutSettings>)=>void}){
 const [layoutOpen,setLayoutOpen]=useState(false); const page=layout.pageLayouts.dividend??{fields:DIV_CHOICES.map(x=>x.key),spans:{symbol:3,name:3,lastBuyDate:3,exDate:3,payDate:3,dividend:3,eligibleShares:3,estimatedDividend:3,actualDividend:3,status:3,reminder:3,source:3,note:6,calendar:6,editor:6}};
 const [selectedDate,setSelectedDate]=useState(today()); const [editing,setEditing]=useState<string|null>(null); const [symbol,setSymbol]=useState(''); const [lastBuyDate,setLastBuyDate]=useState(''); const [exDate,setExDate]=useState(today()); const [payDate,setPayDate]=useState(''); const [dividend,setDividend]=useState(''); const [note,setNote]=useState(''); const h=holdings.find(x=>x.symbol===symbol.trim()); const month=selectedDate.slice(0,7); const monthEvents=useMemo(()=>events.filter(e=>[e.lastBuyDate,e.exDate,e.payDate].some(d=>d?.startsWith(month))),[events,month]);
 const save=()=>{if(!symbol.trim())return Alert.alert('股息日','請選擇或輸入 ETF。'); const item={id:editing??String(Date.now()),symbol:symbol.trim(),name:h?.name??'自訂 ETF',lastBuyDate,exDate,payDate,dividend,note}; setEvents(cur=>editing?cur.map(e=>e.id===editing?item:e):[...cur,item]); setEditing(null); setLastBuyDate('');setPayDate('');setDividend('');setNote('');};
 const edit=(e:DividendEvent)=>{setEditing(e.id);setSymbol(e.symbol);setLastBuyDate(e.lastBuyDate);setExDate(e.exDate);setPayDate(e.payDate);setDividend(e.dividend);setNote(e.note)};
 const renderEvent=(e:DividendEvent)=>{const hh=holdings.find(x=>x.symbol===e.symbol);const eligible=hh?.shares??0;const est=eligible*(Number(e.dividend)||0);const vals:any={symbol:['ETF 代號',e.symbol],name:['ETF 名稱',e.name],lastBuyDate:['最後買進日',e.lastBuyDate||'—'],exDate:['除息日',e.exDate||'—'],payDate:['發放日',e.payDate||'—'],dividend:['每股配息',e.dividend||'—'],eligibleShares:['符合資格股數',`${eligible.toLocaleString('zh-TW')} 股`],estimatedDividend:['預估配息',`${est.toFixed(0)}`],actualDividend:['實際領息','尚未輸入'],status:['配息狀態',new Date(e.payDate||'2999-12-31')<=new Date()?'可能已發放':'待發放'],reminder:['提醒狀態',e.lastBuyDate?'已設定日期':'未設定'],source:['資料來源','手動 / App'],note:['備註',e.note||'—']};return <View key={e.id} style={styles.event}><View style={styles.eventGrid}>{page.fields.filter(k=>!['calendar','editor'].includes(k)).map(k=>{const a=vals[k]??[k,'—'];const span=page.spans[k]||6;return <View key={k} style={[styles.metric,{width:span===6?'100%':span===3?'49%':'32%'}]}><Text style={styles.metricLabel}>{a[0]}</Text><Text style={styles.metricValue} numberOfLines={2}>{a[1]}</Text></View>})}</View><View style={styles.row}><Pressable style={styles.smallBtn} onPress={()=>edit(e)}><Text style={styles.smallText}>修改</Text></Pressable><Pressable style={styles.delBtn} onPress={()=>Alert.alert('刪除股息事件',`確定刪除 ${e.symbol} 這筆股息資料？`,[{text:'取消',style:'cancel'},{text:'刪除',style:'destructive',onPress:()=>setEvents(c=>c.filter(x=>x.id!==e.id))}])}><Text style={styles.delText}>刪除</Text></Pressable></View></View>};
 return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Header title="股息日" subtitle="股息月曆 · 最後買進日 · 除息日 · 發放日" slogan="重要日期集中管理，配息資訊一眼掌握。" onLayoutPress={()=>setLayoutOpen(true)}/><PageLayoutEditor visible={layoutOpen} title="股息頁排版設定" choices={DIV_CHOICES} selected={page.fields} spans={page.spans} onClose={()=>setLayoutOpen(false)} onSave={(fields,spans)=>onLayoutChange({pageLayouts:{...layout.pageLayouts,dividend:{fields,spans}}})}/>
 {page.fields.includes('calendar')?<Card><SectionTitle icon="▦" title="月曆日期" subtitle="點擊日期即可選擇"/><DatePickerField label="查看月份 / 新增事件日期" value={selectedDate} onChange={v=>{setSelectedDate(v);setExDate(v)}} required/><Text style={styles.monthTitle}>{month} 股息事件</Text>{monthEvents.length===0?<Text style={styles.empty}>本月尚無股息事件。</Text>:monthEvents.map(renderEvent)}</Card>:null}
 {page.fields.includes('editor')?<Card><SectionTitle icon="$" title={editing?'修改股息事件':'新增股息事件'} subtitle="ETF 可手動輸入，也可點選目前持有"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.symbols}>{holdings.map(x=><Pressable key={x.symbol} onPress={()=>setSymbol(x.symbol)} style={[styles.symbolChip,symbol===x.symbol&&styles.symbolOn]}><Text style={[styles.symbolText,symbol===x.symbol&&styles.symbolTextOn]}>{x.symbol}</Text></Pressable>)}</ScrollView><Field label="ETF 代號" value={symbol} onChange={setSymbol}/><Text style={styles.name}>{h?.name??(symbol?'輸入後若為持有 ETF 將自動帶入名稱':'')}</Text><DatePickerField label="最後買進日" value={lastBuyDate} onChange={setLastBuyDate}/><DatePickerField label="除息日" value={exDate} onChange={setExDate}/><DatePickerField label="股息發放日" value={payDate} onChange={setPayDate}/><Field label="每股配息" value={dividend} onChange={setDividend} keyboard/><Field label="備註" value={note} onChange={setNote}/><Pressable style={styles.save} onPress={save}><Text style={styles.saveText}>{editing?'儲存修改':'新增股息事件'}</Text></Pressable></Card>:null}
 </ScrollView>;
}
function Field({label,value,onChange,keyboard}:{label:string;value:string;onChange:(v:string)=>void;keyboard?:boolean}){return <View style={{marginTop:10}}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType={keyboard?'decimal-pad':'default'} style={styles.input} placeholderTextColor={palette.muted}/></View>}
const styles=StyleSheet.create({content:{paddingBottom:98},monthTitle:{color:palette.text,fontWeight:'900',fontSize:13,marginTop:15},empty:{color:palette.muted,fontSize:11,paddingVertical:16},event:{padding:12,borderWidth:1,borderColor:palette.line,borderRadius:14,backgroundColor:palette.surfaceSoft,marginTop:8},eventGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:7},metric:{backgroundColor:'#fff',borderRadius:10,padding:8,minHeight:58},metricLabel:{fontSize:8.5,color:palette.muted},metricValue:{fontSize:11,fontWeight:'900',color:palette.text,textAlign:'right',marginTop:5},row:{flexDirection:'row',gap:8,marginTop:8},smallBtn:{paddingHorizontal:14,minHeight:36,borderRadius:10,backgroundColor:palette.greenSoft,justifyContent:'center'},smallText:{color:palette.green,fontSize:10,fontWeight:'900'},delBtn:{paddingHorizontal:14,minHeight:36,borderRadius:10,backgroundColor:palette.redSoft,justifyContent:'center'},delText:{color:palette.red,fontSize:10,fontWeight:'900'},symbols:{gap:7,paddingBottom:5},symbolChip:{minHeight:38,paddingHorizontal:12,borderRadius:19,borderWidth:1,borderColor:palette.line,justifyContent:'center'},symbolOn:{backgroundColor:palette.greenSoft,borderColor:'#B9E8D4'},symbolText:{fontSize:10,fontWeight:'900',color:palette.text},symbolTextOn:{color:palette.green},label:{color:palette.muted,fontSize:10,fontWeight:'800',marginBottom:5},input:{minHeight:45,borderWidth:1,borderColor:palette.line,borderRadius:12,paddingHorizontal:12,color:palette.text,fontSize:15},name:{color:palette.green,fontSize:11,fontWeight:'800',marginTop:5},save:{minHeight:46,borderRadius:13,backgroundColor:palette.green,alignItems:'center',justifyContent:'center',marginTop:14},saveText:{color:'#fff',fontWeight:'900'}});
