import React, { useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, View } from 'react-native';
import Svg, { Defs, LinearGradient, Rect, Stop } from 'react-native-svg';
import { ScaledText as Text } from './ScaledText';
import { palette } from './Ui';

function clamp(v:number,min=0,max=1){return Math.max(min,Math.min(max,v));}
function hsvToHex(h:number,s:number,v:number){const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}const q=(n:number)=>Math.round((n+m)*255).toString(16).padStart(2,'0').toUpperCase();return `#${q(r)}${q(g)}${q(b)}`;}
function hexToHsv(hex:string){const h=hex.replace('#','').slice(0,6);if(!/^[0-9A-Fa-f]{6}$/.test(h))return {h:160,s:.75,v:.65};const r=parseInt(h.slice(0,2),16)/255,g=parseInt(h.slice(2,4),16)/255,b=parseInt(h.slice(4,6),16)/255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let hue=0;if(d){if(max===r)hue=60*(((g-b)/d)%6);else if(max===g)hue=60*((b-r)/d+2);else hue=60*((r-g)/d+4)}if(hue<0)hue+=360;return {h:hue,s:max?d/max:0,v:max};}
const quick=['#FFFFFF','#8E9BAE','#D4AF37','#30D158','#FF453A','#0A84FF','#BF5AF2','#111827'];

export default function ColorPalettePicker({label,value,onChange,allowTheme=true}:{label:string;value?:string;onChange:(v:any)=>void;allowTheme?:boolean}){
 const [open,setOpen]=useState(false);
 const safe=value&&/^#[0-9A-Fa-f]{6,8}$/.test(value)?`#${value.replace('#','').slice(0,6).toUpperCase()}`:'#FFFFFF';
 const hsv0=useMemo(()=>hexToHsv(safe),[safe]);
 const [hue,setHue]=useState(hsv0.h); const [sat,setSat]=useState(hsv0.s); const [val,setVal]=useState(hsv0.v);
 const [draft,setDraft]=useState(safe);
 useEffect(()=>{if(open){const x=hexToHsv(safe);setHue(x.h);setSat(x.s);setVal(x.v);setDraft(safe)}},[open,safe]);
 const hueColor=hsvToHex(hue,1,1);
 const syncDraft=(h:number,s:number,v:number)=>{setHue(h);setSat(s);setVal(v);setDraft(hsvToHex(h,s,v))};
 const openPalette=()=>{const x=hexToHsv(safe);setHue(x.h);setSat(x.s);setVal(x.v);setDraft(safe);setOpen(true)};
 const confirmColor=()=>{onChange(draft);setOpen(false)};
 const cancel=()=>{setOpen(false)};
 return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.row}>{allowTheme?<Pressable onPress={()=>onChange(undefined)} style={[styles.themeBtn,!value&&styles.selected]}><Text style={styles.buttonText}>🔗 跟隨主題</Text></Pressable>:null}<Pressable onPress={openPalette} style={styles.colorBtn}><View style={[styles.colorBox,{backgroundColor:safe}]}/><Text style={styles.buttonText}>{value?'自訂色':'選擇色盤'}</Text></Pressable></View>
 <Modal transparent visible={open} animationType="fade" onRequestClose={cancel}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.head}><Text style={styles.title}>{label}</Text><Pressable onPress={cancel}><Text style={styles.done}>取消</Text></Pressable></View><Text style={styles.hint}>先在色盤挑選並預覽，按「確定使用此顏色」才套用目前項目。</Text><View style={styles.quick}>{quick.map(c=><Pressable key={c} onPress={()=>{const x=hexToHsv(c);syncDraft(x.h,x.s,x.v)}} style={[styles.swatch,{backgroundColor:c},draft===c&&styles.swatchSelected]}/>)}</View><View style={styles.paletteWrap} onStartShouldSetResponder={()=>true} onMoveShouldSetResponder={()=>true} onResponderGrant={e=>{const s=clamp(e.nativeEvent.locationX/280),v=1-clamp(e.nativeEvent.locationY/190);syncDraft(hue,s,v)}} onResponderMove={e=>{const s=clamp(e.nativeEvent.locationX/280),v=1-clamp(e.nativeEvent.locationY/190);syncDraft(hue,s,v)}}><Svg width="280" height="190"><Defs><LinearGradient id="sat" x1="0" y1="0" x2="1" y2="0"><Stop offset="0" stopColor="#FFFFFF"/><Stop offset="1" stopColor={hueColor}/></LinearGradient><LinearGradient id="val" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor="#000" stopOpacity="0"/><Stop offset="1" stopColor="#000" stopOpacity="1"/></LinearGradient></Defs><Rect width="280" height="190" fill="url(#sat)"/><Rect width="280" height="190" fill="url(#val)"/></Svg><View pointerEvents="none" style={[styles.cursor,{left:sat*280-8,top:(1-val)*190-8}]}/></View><View style={styles.hueWrap} onStartShouldSetResponder={()=>true} onMoveShouldSetResponder={()=>true} onResponderGrant={e=>syncDraft(clamp(e.nativeEvent.locationX/280)*360,sat,val)} onResponderMove={e=>syncDraft(clamp(e.nativeEvent.locationX/280)*360,sat,val)}><Svg width="280" height="28"><Defs><LinearGradient id="hue" x1="0" y1="0" x2="1" y2="0"><Stop offset="0" stopColor="#F00"/><Stop offset=".17" stopColor="#FF0"/><Stop offset=".33" stopColor="#0F0"/><Stop offset=".5" stopColor="#0FF"/><Stop offset=".67" stopColor="#00F"/><Stop offset=".83" stopColor="#F0F"/><Stop offset="1" stopColor="#F00"/></LinearGradient></Defs><Rect width="280" height="28" rx="8" fill="url(#hue)"/></Svg></View><View style={styles.previewRow}><View style={[styles.preview,{backgroundColor:draft}]}/><Text style={styles.previewText}>目前選擇</Text></View><Pressable style={styles.apply} onPress={confirmColor}><Text style={styles.applyText}>✓ 確定使用此顏色</Text></Pressable>{allowTheme?<Pressable style={styles.themeApply} onPress={()=>{onChange(undefined);setOpen(false)}}><Text style={styles.buttonText}>恢復跟隨主題</Text></Pressable>:null}</View></View></Modal></View>;
}

const styles=StyleSheet.create({field:{marginTop:10},label:{fontSize:10,color:palette.muted,fontWeight:'900',marginBottom:6},row:{flexDirection:'row',alignItems:'center',gap:8,flexWrap:'wrap'},themeBtn:{minHeight:42,paddingHorizontal:12,borderRadius:10,borderWidth:1,borderColor:palette.line,justifyContent:'center'},selected:{borderColor:'#D4AF37',backgroundColor:'rgba(212,175,55,.12)'},colorBtn:{minHeight:42,paddingHorizontal:10,borderRadius:10,borderWidth:1,borderColor:palette.line,flexDirection:'row',alignItems:'center',gap:8},colorBox:{width:24,height:24,borderRadius:6,borderWidth:1,borderColor:palette.line},buttonText:{fontSize:10,fontWeight:'900',color:palette.text},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.62)',alignItems:'center',justifyContent:'center',padding:18},sheet:{width:'100%',maxWidth:340,backgroundColor:'#111827',borderRadius:18,padding:16,borderWidth:1,borderColor:palette.line},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:6},title:{fontSize:17,fontWeight:'900',color:palette.text},done:{fontWeight:'900',color:palette.muted},hint:{fontSize:10,lineHeight:15,color:palette.muted,marginBottom:12},quick:{flexDirection:'row',gap:7,flexWrap:'wrap',marginBottom:12},swatch:{width:28,height:28,borderRadius:7,borderWidth:1,borderColor:palette.line},swatchSelected:{borderWidth:2,borderColor:'#FFFFFF'},paletteWrap:{width:280,height:190,alignSelf:'center',borderRadius:10,overflow:'hidden'},cursor:{position:'absolute',width:16,height:16,borderRadius:8,borderWidth:2,borderColor:'#fff'},hueWrap:{width:280,height:28,alignSelf:'center',marginTop:12},previewRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:14},preview:{width:44,height:44,borderRadius:10,borderWidth:1,borderColor:palette.line},previewText:{fontSize:12,fontWeight:'900',color:palette.text},apply:{minHeight:46,borderRadius:12,backgroundColor:'#D4AF37',alignItems:'center',justifyContent:'center',marginTop:12},applyText:{color:'#111827',fontWeight:'900'},themeApply:{minHeight:42,borderRadius:12,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center',marginTop:8}});
