import React, { useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { palette } from './Ui';

const pad=(n:number)=>String(n).padStart(2,'0');
const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=(v:string)=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v); if(!m)return new Date(); const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3])); return Number.isNaN(d.getTime())?new Date():d;};

export default function DatePickerField({label,value,onChange,required=false}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){
  const [open,setOpen]=useState(false); const [cursor,setCursor]=useState(()=>parse(value));
  const days=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(); const out:(number|null)[]=[]; for(let i=0;i<first;i++)out.push(null); for(let d=1;d<=count;d++)out.push(d); while(out.length%7)out.push(null); return out;},[cursor]);
  const select=(day:number)=>{const d=new Date(cursor.getFullYear(),cursor.getMonth(),day); onChange(iso(d)); setOpen(false);};
  return <View style={styles.wrap}><Text style={styles.label}>{label}{required?' *':''}</Text><View style={styles.row}><Pressable style={styles.field} onPress={()=>{setCursor(parse(value));setOpen(true)}}><Text style={styles.value}>{value||'選擇日期'}</Text><Text style={styles.icon}>📅</Text></Pressable><Pressable style={styles.today} onPress={()=>onChange(iso(new Date()))}><Text style={styles.todayText}>今天</Text></Pressable></View>
    <Modal transparent visible={open} animationType="fade" onRequestClose={()=>setOpen(false)}><Pressable style={styles.backdrop} onPress={()=>setOpen(false)}><Pressable style={styles.modal} onPress={()=>{}}>
      <View style={styles.head}><Pressable style={styles.nav} onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><Text style={styles.navText}>‹</Text></Pressable><Text style={styles.month}>{cursor.getFullYear()} 年 {cursor.getMonth()+1} 月</Text><Pressable style={styles.nav} onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><Text style={styles.navText}>›</Text></Pressable></View>
      <View style={styles.week}>{['日','一','二','三','四','五','六'].map(w=><Text key={w} style={styles.weekText}>{w}</Text>)}</View><View style={styles.grid}>{days.map((d,i)=>{const selected=Boolean(d)&&value===`${cursor.getFullYear()}-${pad(cursor.getMonth()+1)}-${pad(d as number)}`; return <View key={i} style={styles.cell}>{d?<Pressable onPress={()=>select(d as number)} style={[styles.day,selected&&styles.dayOn]}><Text style={[styles.dayText,selected&&styles.dayTextOn]}>{d}</Text></Pressable>:null}</View>})}</View>
      <Pressable style={styles.close} onPress={()=>setOpen(false)}><Text style={styles.closeText}>取消</Text></Pressable>
    </Pressable></Pressable></Modal>
  </View>;
}
const styles=StyleSheet.create({wrap:{flex:1},label:{color:palette.muted,fontSize:10,fontWeight:'800',marginBottom:6},row:{flexDirection:'row',gap:8},field:{flex:1,minHeight:46,borderWidth:1,borderColor:palette.line,borderRadius:12,paddingHorizontal:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#fff'},value:{color:palette.text,fontSize:14,fontWeight:'800'},icon:{fontSize:16},today:{minWidth:58,borderRadius:12,backgroundColor:palette.greenSoft,alignItems:'center',justifyContent:'center',paddingHorizontal:10},todayText:{color:palette.green,fontWeight:'900',fontSize:11},backdrop:{flex:1,backgroundColor:'rgba(15,23,42,0.35)',alignItems:'center',justifyContent:'center',padding:20},modal:{width:'100%',maxWidth:390,backgroundColor:'#fff',borderRadius:20,padding:16},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},month:{color:palette.text,fontSize:17,fontWeight:'900'},nav:{width:44,height:44,alignItems:'center',justifyContent:'center'},navText:{fontSize:30,color:palette.green},week:{flexDirection:'row',marginTop:8},weekText:{width:'14.2857%',textAlign:'center',color:palette.muted,fontSize:11,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:6},cell:{width:'14.2857%',aspectRatio:1,alignItems:'center',justifyContent:'center'},day:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'},dayOn:{backgroundColor:palette.green},dayText:{color:palette.text,fontSize:13,fontWeight:'800'},dayTextOn:{color:'#fff'},close:{minHeight:44,alignItems:'center',justifyContent:'center',marginTop:8},closeText:{color:palette.muted,fontWeight:'900'}});
