import React, { ReactNode, createContext, useContext } from 'react';
import { Image, ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';

export const palette = {
  bg: '#F4FAFC', surface: '#FFFFFF', surfaceSoft: '#F1F8FA', text: '#0B2B4B', muted: '#6F8297',
  green: '#12A875', greenSoft: '#E6F8F0', blue: '#2889DF', blueSoft: '#EAF5FF', red: '#E54A45',
  redSoft: '#FFF0EF', orange: '#D98A21', orangeSoft: '#FFF5E7', line: '#DFEAF0', track: '#DDE8EE',
};

type ThemeUi={cardOpacity:number;cardTint:string;cardBackgroundImageUri:string;cardBackgroundImageOpacity:number;cardRadius:number;cardPadding:number;text:string;muted:string;accent:string;positive:string;negative:string;fontScale:number;wrapText:boolean;textAlign:'left'|'center'|'right'};
const defaultTheme:ThemeUi={cardOpacity:92,cardTint:'#FFFFFF',cardBackgroundImageUri:'',cardBackgroundImageOpacity:22,cardRadius:12,cardPadding:14,text:palette.text,muted:palette.muted,accent:palette.green,positive:palette.red,negative:palette.green,fontScale:100,wrapText:true,textAlign:'left'};
const ThemeContext=createContext<ThemeUi>(defaultTheme);
export function ThemeProvider({value,children}:{value:Partial<ThemeUi>;children:ReactNode}){return <ThemeContext.Provider value={{...defaultTheme,...value}}>{children}</ThemeContext.Provider>}
export function useAppTheme(){return useContext(ThemeContext)}
function alphaHex(hex:string,opacity:number){const h=hex.replace('#','');if(h.length!==6)return `rgba(255,255,255,${opacity/100})`;const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);return `rgba(${r},${g},${b},${Math.max(0,Math.min(1,opacity/100))})`}

export function Card({ children, style }: { children: ReactNode; style?: any }) {
  const t=useAppTheme(); const radius=Math.max(0,Math.min(28,t.cardRadius)); const padding=Math.max(8,Math.min(28,t.cardPadding));
  return <View style={[styles.card,{borderRadius:radius,backgroundColor:alphaHex(t.cardTint,t.cardOpacity),borderColor:alphaHex('#FFFFFF',Math.min(100,t.cardOpacity+4))},style]}>
    {t.cardBackgroundImageUri?<View pointerEvents="none" style={[StyleSheet.absoluteFill,{borderRadius:radius,overflow:'hidden'}]}><ImageBackground source={{uri:t.cardBackgroundImageUri}} resizeMode="cover" imageStyle={{opacity:Math.max(0,Math.min(1,t.cardBackgroundImageOpacity/100))}} style={StyleSheet.absoluteFill}/></View>:null}
    <View style={{padding}}>{children}</View>
  </View>;
}
export function EtfCodeBadge({symbol}:{symbol:string}){const t=useAppTheme();return <View style={[styles.etfBadge,{backgroundColor:t.accent}]}><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.78} style={styles.etfBadgeText}>{symbol}</Text></View>}
export function SectionTitle({ icon, title, subtitle }: { icon?: string; title: string; subtitle?: string }) {
  const t=useAppTheme(); return <View style={styles.sectionTitleRow}>{!!icon&&<Text style={[styles.sectionIcon,{color:t.accent}]}>{icon}</Text>}<View style={{flex:1,minWidth:0}}><Text style={[styles.sectionTitle,{color:t.text,fontSize:20*t.fontScale/100}]}>{title}</Text>{!!subtitle&&<Text style={[styles.sectionSubtitle,{color:t.muted,fontSize:12*t.fontScale/100}]}>{subtitle}</Text>}</View><Text style={[styles.chevron,{color:t.text}]}>›</Text></View>;
}
export function Progress({ value, tone = 'green' }: { value: number; tone?: 'green' | 'blue' | 'red' }) { const t=useAppTheme(); const width=`${Math.max(0,Math.min(100,value))}%` as any; const backgroundColor=tone==='blue'?palette.blue:tone==='red'?t.positive:t.accent; return <View style={styles.progressTrack}><View style={[styles.progressFill,{width,backgroundColor}]}/></View> }
export function Chip({ text, tone = 'green' }: { text: string; tone?: 'green' | 'blue' | 'orange' | 'gray' | 'red' }) { const t=useAppTheme(); const colors={green:[alphaHex(t.accent,12),t.accent],blue:[palette.blueSoft,palette.blue],orange:[palette.orangeSoft,palette.orange],red:[palette.redSoft,t.positive],gray:['#EEF2F5',t.muted]}[tone]; return <View style={[styles.chip,{backgroundColor:colors[0]}]}><Text style={[styles.chipText,{color:colors[1],fontSize:12*t.fontScale/100}]}>{text}</Text></View> }
export function NavButton({ icon, label, active, onPress }: { icon: string; label: string; active: boolean; onPress: () => void }) { const t=useAppTheme(); return <Pressable onPress={onPress} style={styles.navButton}><Text style={[styles.navIcon,{color:active?t.accent:t.muted,fontSize:23*t.fontScale/100}]}>{icon}</Text><Text style={[styles.navLabel,{color:active?t.accent:t.muted,fontSize:11*t.fontScale/100},active&&{fontWeight:'900'}]}>{label}</Text></Pressable> }
export function Header({ title, subtitle, slogan, onLayoutPress }: { title: string; subtitle: string; slogan?: string; onLayoutPress?: () => void }) { const t=useAppTheme(); return <View style={styles.header}><View style={styles.brandRow}><Image source={require('../../assets/etf-finance-logo.png')} style={styles.logoImage}/><View style={{flex:1,minWidth:0}}><Text style={[styles.brand,{color:t.text,fontSize:26*t.fontScale/100}]}>{title||'ETF財務管家'}</Text><Text style={[styles.brandSub,{color:t.muted,fontSize:13*t.fontScale/100}]}>{subtitle||'投資資料與目標管理'}</Text></View>{onLayoutPress?<Pressable onPress={onLayoutPress} hitSlop={10} accessibilityLabel="此頁排版設定" style={styles.headerAction}><Text style={[styles.headerIcon,{color:t.text}]}>⚙</Text></Pressable>:null}</View>{!!slogan?<View style={styles.sloganRow}><Text style={[styles.slogan,{color:t.muted,fontSize:11*t.fontScale/100}]}>{slogan}</Text><View style={[styles.sloganLine,{backgroundColor:t.accent}]}/></View>:null}</View> }
export function RefreshText({ lastSuccessAt, error, onPress }: { lastSuccessAt?: number; error?: string; onPress: () => void }) { const t=useAppTheme(); const time=lastSuccessAt?new Date(lastSuccessAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'--:--:--'; return <Pressable onPress={onPress} style={styles.refreshRow}><Text style={[styles.refreshText,{color:error?palette.orange:t.muted,fontSize:11*t.fontScale/100}]}>{error?`TWSE 更新異常 · ${time}`:`TWSE · ${time}`}</Text><Text style={[styles.refreshIcon,{color:t.text}]}>↻</Text></Pressable> }
const styles=StyleSheet.create({card:{position:'relative',borderWidth:1,marginHorizontal:16,marginBottom:12,shadowColor:'#36556E',shadowOpacity:.07,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:2},etfBadge:{width:76,height:32,borderRadius:8,alignItems:'center',justifyContent:'center',paddingHorizontal:7},etfBadgeText:{color:'#fff',fontWeight:'900',fontSize:15,textAlign:'center',letterSpacing:.3},sectionTitleRow:{flexDirection:'row',alignItems:'flex-start',gap:9,marginBottom:14},sectionIcon:{fontSize:24,width:30},sectionTitle:{fontWeight:'900',flexShrink:1},sectionSubtitle:{marginTop:3,lineHeight:18,flexWrap:'wrap'},chevron:{fontSize:30,lineHeight:24},progressTrack:{height:10,borderRadius:99,backgroundColor:palette.track,overflow:'hidden'},progressFill:{height:'100%',borderRadius:99},chip:{alignSelf:'flex-start',paddingHorizontal:12,paddingVertical:6,borderRadius:99},chipText:{fontWeight:'800',fontSize:12},navButton:{flex:1,alignItems:'center',justifyContent:'center',paddingTop:6,paddingBottom:5},navIcon:{fontSize:23},navLabel:{marginTop:2,fontSize:11,fontWeight:'700'},header:{paddingHorizontal:16,paddingTop:8,paddingBottom:10},brandRow:{flexDirection:'row',alignItems:'center'},logoImage:{width:46,height:46,borderRadius:12,marginRight:10},brand:{fontWeight:'900',flexWrap:'wrap'},brandSub:{fontSize:13,marginTop:1,flexWrap:'wrap'},headerAction:{marginLeft:12,width:42,height:42,alignItems:'center',justifyContent:'center',borderRadius:12},headerIcon:{fontSize:25},sloganRow:{marginTop:10,alignItems:'flex-end'},slogan:{textAlign:'right',lineHeight:16,fontStyle:'italic'},sloganLine:{width:68,height:3,borderRadius:99,marginTop:4},refreshRow:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:6,marginTop:2},refreshText:{fontSize:11},refreshIcon:{fontSize:18}});
