const fs=require('fs');
const must=(path,parts)=>{const s=fs.existsSync(path)?fs.readFileSync(path,'utf8'):'';for(const p of parts){if(!s.includes(p)){console.error(`[BROKER RED/GREEN] ${path} missing: ${p}`);process.exitCode=1;}}};
must('src/data/brokerProfiles.ts',['export type BrokerProfile','DEFAULT_BROKER_PROFILE_ID','HUANAN_YONGCHANG_PROFILE_ID','resolveBrokerProfile','calculateBrokerCommission']);
must('src/v3/model.ts',['brokerProfileId?: string;','brokerProfiles: BrokerProfile[];','defaultBrokerProfileId: string;']);
must('src/v3/storage.ts',['normalizeBrokerProfiles','const brokerProfiles=normalizeBrokerProfiles','defaultBrokerProfileId']);
must('src/v3/engine.ts',['configureBrokerProfiles','resolveBrokerProfile','brokerProfileId']);
must('src/v3/screensBase.tsx',["|'broker'",'券商 Profile 管理','brokerProfiles:BrokerProfile[]','brokerProfileId:string','onBrokerProfilesChange']);
must('App.tsx',['configureBrokerProfiles','brokerProfiles:state.brokerProfiles','defaultBrokerProfileId={state.defaultBrokerProfileId}','onBrokerProfilesChange','brokerProfileId:brokerProfile.id']);
must('src/utils/etfCalculators.ts',['resolveTransactionBrokerProfile','calculateBrokerCommission','calculateBrokerSellTax']);
if(!process.exitCode)console.log('BROKER_MODULE_RESTORE_CONTRACT_OK');
