const fs=require('fs');
const t=fs.readFileSync('src/v3/monitorTemplates.ts','utf8');
const s=fs.readFileSync('src/v3/screens.tsx','utf8');
const o=fs.readFileSync('src/services/floatingOverlay.ts','utf8');
const native=fs.readFileSync('modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingInvestmentBotService.kt','utf8');
let failed=0;const check=(ok,msg)=>{if(ok)console.log('PASS',msg);else{console.error('FAIL',msg);failed++}};
const templateRows=[...t.matchAll(/\{id:'([^']+)',name:'([^']+)',fields:\[([^\]]*)\],columns:(\d)(?:,compact:true)?(?:,nativeMode:'([^']+)')?\}/g)];
check(templateRows.length===12,'exactly 12 monitor templates are declared');
check(templateRows.every(x=>x[3].trim().length>0),'every template has composition fields');
check(templateRows.every(x=>x[5]==='table'||x[5]==='puzzle'||x[5]==='strip'),'every template declares nativeMode');
check(t.includes("export const templateDefaultFields=(id:MonitorDisplayMode)=>[...monitorTemplate(id).fields]"),'template default field helper exists');
check(s.includes('function MonitorTemplateEditor'),'template editor component exists');
check(s.includes('模板內容與組合項目'),'template editor exposes composition content');
check(s.includes('套用此模板組合'),'template editor can apply template composition');
check(s.includes('function MonitorChoice'),'monitor control choice is separate from generic editable Choice');
check(s.includes('setMonitorTemplateEdit(t.id)')&&s.includes('fields:templateDefaultFields(t.id)'),'template press selects, applies composition, and opens editor');
check(s.includes('function MonitorFieldPicker')&&s.includes('onPress={()=>onEdit(key)}')&&s.includes('onEdit={key=>setMonitorFieldEdit(key)}'),'monitor field chips use explicit field edit target');
check(o.includes('mode:template.nativeMode'),'payload uses explicit template nativeMode');
check(o.includes('templateFields:template.fields'),'payload carries template composition for native fallback');
check(o.includes('profile?.fieldsCustomized===true'),'payload distinguishes template composition from custom field composition');
check(native.includes('private fun signed2(v:Double):String='),'native renderer retains signed percentage formatter');
check(native.includes('private fun selectedMetricLines(): MutableList<String>'),'native strip/legacy renderer retains field line builder');
check(native.includes('private fun renderText():String'),'native strip/legacy renderer retains text renderer');
const tableStart=native.indexOf('  private fun renderTableOverlay() {');
const puzzleStart=native.indexOf('  private fun renderPuzzleOverlay() {',tableStart+1);
const table=tableStart>=0&&puzzleStart>tableStart?native.slice(tableStart,puzzleStart):'';
check(table.includes('fields.chunked(max(1,columnCount))')&&table.includes('for(group in groups)'),'native table renderer preserves all configured fields by chunking overflow columns');
check(table.includes('"totalAssets" to "總資產"'),'native table renderer labels totalAssets');
check(table.includes('"dividend" to "股息事件"'),'native table renderer labels dividend');
check(table.includes('"totalAssets"->money(payload.optDouble("totalAssets",0.0))'),'native table renderer reads canonical totalAssets payload');
check(table.includes('fun dividendText():String=if(payload.optString("dividendSymbol").isNotBlank())')&&table.includes('"dividend"->dividendText()'),'native table renderer reads dividend payload');
if(failed){console.error(`MONITOR TEMPLATE CONTRACT: FAIL (${failed})`);process.exit(1)}
console.log('MONITOR TEMPLATE CONTRACT: PASS');
