const fs=require('fs');
const checks=[];const add=(n,ok)=>checks.push([n,!!ok]);
const read=p=>fs.readFileSync(p,'utf8');
const app=JSON.parse(read('app.json')),pkg=JSON.parse(read('package.json'));
const ff=read('src/v3/financeFormat.ts'),eng=read('src/v3/engine.ts'),ov=read('src/services/floatingOverlay.ts'),model=read('src/v3/model.ts'),screen=read('src/v3/screens.tsx'),appsrc=read('App.tsx'),kt=read('modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingInvestmentBotService.kt'),formula=read('src/v3/formulaEngine.ts'),gm=read('src/v3/globalMetrics.ts');
add('version 3.5.0',app.expo.version==='3.5.0'&&app.expo.runtimeVersion==='3.5.0'&&app.expo.android.versionCode===36&&pkg.version==='3.5.0');
add('trade cost floor',/Math\.floor\(price\*shares\)/.test(ff));
add('formula engine no eval',!/(^|[^A-Za-z])eval\s*\(|new\s+Function/.test(formula));
add('formula whitelist',/SUM.*AVG.*MIN.*MAX.*IF.*ROUND.*FLOOR.*CEIL.*ABS/.test(formula));
add('global metrics provenance',/source:string;formula:string;asOf:number;isStale:boolean/.test(gm));
add('inventory pnl total',/totalPnl=priceUnrealizedPnl/.test(eng));
add('holding pnl pure',/const pnl=pricePnl/.test(eng));
add('chronological cost basis',/trades[\s\S]*?\.sort/.test(eng)&&/poolTradeCost/.test(eng)&&/realizedCashPnl/.test(eng));
add('table mode type',/\|'table'/.test(model));
add('selectable live fields',/changePct.*shares.*pureCost.*instantPnl.*todayPnl.*volume/.test(model));
add('rows 1-30 UI',/floatingRows/.test(model)&&/min=\{1\} max=\{30\}/.test(screen));
add('native table renderer',/renderTableOverlay/.test(kt)&&/LinearLayout/.test(kt));
add('native pure-cost pnl',/pureCost/.test(kt)&&/price \* shares - pureCost/.test(kt));
add('TW positive red negative green defaults',/#E54A45/.test(model)&&/#12A875/.test(model));
add('overlay summary',/totalCost/.test(ov)&&/marketValue/.test(ov)&&/instantPnl/.test(ov));
add('foreground mutual exclusion',/next==='active'.*stopFloatingOverlay/.test(appsrc));
add('background delayed state recheck',/AppState\.currentState!=='active'/.test(appsrc));
add('safe realtime throttle',/sec <= 0\.0\) 1000L/.test(kt)&&/max\(250L/.test(kt));
const bad=checks.filter(x=>!x[1]);for(const [n,ok] of checks)console.log(`${ok?'PASS':'FAIL'} ${n}`);if(bad.length){process.exit(1)}console.log(`V350_REGRESSION_FROM_V342: PASS (${checks.length}/${checks.length})`);
