const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const exists=p=>fs.existsSync(path.join(root,p));
const pkg=JSON.parse(read('package.json'));const app=JSON.parse(read('app.json')).expo;const eas=JSON.parse(read('eas.json'));
const checks=[];const add=(name,ok,detail='')=>checks.push({name,ok:!!ok,detail});
const screens=read('src/v3/screens.tsx'),model=read('src/v3/model.ts'),storage=read('src/v3/storage.ts'),globalEditor=read('src/v3/GlobalCardDesigner.tsx'),chart=read('src/v3/ChartEngine2.tsx'),ai=read('src/v3/AiAssistantModal.tsx'),overlay=read('src/services/floatingOverlay.ts'),native=read('modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingInvestmentBotService.kt'),nativeModule=read('modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingInvestmentBotModule.kt'),manifest=read('modules/floating-investment-bot/android/src/main/AndroidManifest.xml'),plugin=read('plugins/withAlternateIcons.js');
add('package version 3.6.0',pkg.version==='3.6.0');
add('app version/runtime 3.6.0',app.version==='3.6.0'&&app.runtimeVersion==='3.6.0');
add('Android versionCode 37',app.android?.versionCode===37);
add('Expo SDK pinned ~57.0.21',pkg.dependencies?.expo==='~57.0.21');
add('preview APK + preview channel',eas.build?.preview?.android?.buildType==='apk'&&eas.build?.preview?.channel==='preview');
add('storage schema 12',storage.includes('const SCHEMA=12;'));
add('Global Editor persists individual field settings',globalEditor.includes('persistCard=')&&globalEditor.includes('onApply({fields:[...fields],fieldSpans:spans,fieldConfigs:next})'));
add('Global Editor effects + live preview',globalEditor.includes("effectStrength")&&globalEditor.includes('即時預覽'));
add('App renderer consumes field effect',screens.includes('fxStrength')&&screens.includes("cfg.effect??'none'"));
add('Settings sub-tabs adaptive height',screens.includes('settingsMinorNav:{gap:8')&&screens.includes('minHeight:48')&&screens.includes('lineHeight:18'));
add('Editor navigation-bar immersive control',screens.includes('setImmersiveEditor(true)')&&nativeModule.includes('setImmersiveEditor'));
add('Chart single tap changes type immediately',chart.includes('if(prefs.chartInteraction?.singleTapCycle!==false)cycle()'));
add('Chart remembers last style',chart.includes('@etf-finance-manager/chart-last:')&&chart.includes('AsyncStorage.setItem(rememberKey'));
add('AI dividend query has scope parser',ai.includes('function dividendIntent')&&ai.includes("scope:next?'next'"));
add('AI latest dividend is one-record path',ai.includes("intent.scope==='latest'||intent.scope==='next'")&&ai.includes('formatDividendInfo(info)'));
add('AI in-app diagnosis',ai.includes('App 診斷｜${APP_DISPLAY_VERSION}'));
add('Legacy Cross-App BOT implementation removed',!exists('src/v3/FloatingInvestmentBot.tsx')&&!model.includes('floatingCrossApp')&&!model.includes('floatingBot:boolean'));
add('Floating monitor payload owns style/schedule/lock',overlay.includes('fieldStyles:profile?.fieldStyles??{}')&&overlay.includes('schedule:profile?.schedule??null')&&overlay.includes('locked:profile?.locked??false'));
add('Native overlay consumes fieldStyles',native.includes('private fun fieldStyle')&&native.includes('styledFieldText'));
add('Native overlay lock blocks drag + resize',native.includes('if (payload.optBoolean("locked", false))')&&native.includes('return@setOnTouchListener true'));
add('Native schedule receiver + boot restore',exists('modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingMonitorScheduleReceiver.kt')&&manifest.includes('BOOT_COMPLETED'));
add('Native App Icon switcher',nativeModule.includes('setAppIcon')&&nativeModule.includes('getCurrentAppIcon'));
add('Alternate icon config plugin',plugin.includes('activity-alias')&&plugin.includes('shortcuts.xml'));
for(let i=1;i<=10;i++){const n=String(i).padStart(2,'0');const f=`assets/app-icons/icon-${n}.png`;add(`App icon ${n} asset`,exists(f)&&fs.statSync(path.join(root,f)).size>20000);}
add('App Icon Center UI',exists('src/v3/AppIconCenter.tsx')&&screens.includes("section==='appicon'"));
add('Static launcher shortcuts wired',plugin.includes('v360_shortcut_add_buy')&&read('App.tsx').includes("u.includes('://ai')"));
const allFiles=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.git'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else allFiles.push(p)}}walk(path.join(root,'src'));
const rnSafeAreaOffenders=allFiles.filter(f=>/\.(ts|tsx)$/.test(f)&&/import[^;]*SafeAreaView[^;]*from ['\"]react-native['\"]/.test(fs.readFileSync(f,'utf8')));
add('No deprecated React Native SafeAreaView imports',rnSafeAreaOffenders.length===0,rnSafeAreaOffenders.map(x=>path.relative(root,x)).join(','));
const pass=checks.filter(x=>x.ok).length;for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'} ${c.name}${c.detail?` :: ${c.detail}`:''}`);console.log(`\nV3.6.0 Native audit ${pass}/${checks.length}`);if(pass!==checks.length)process.exit(1);
