const areas=['system','keyboard','editor','widget','overlay','monitor-template','watchlist','apk-matrix'];

const items=[
  {id:'system.safe-area-navigation',area:'system',title:'System navigation and safe-area behavior',verification:'hybrid',surface:'app shell',staticHooks:[{type:'contains',path:'App.tsx',text:'SafeAreaView'},{type:'contains',path:'App.tsx',text:"edges={['top','left','right','bottom']}"}],deviceSteps:['Test gesture navigation and three-button navigation.','Open every active V3 tab and verify bottom controls remain above the system navigation area.','Repeat on a device or emulator with display cutout simulation enabled.'],expected:'No active screen, modal footer, tab control, or floating action control is obscured by Android system bars or cutouts.',evidence:'Screenshots for gesture and three-button navigation plus device/OS notes.'},
  {id:'system.immersive-foreground',area:'system',title:'Immersive navigation reapplies after foregrounding',verification:'hybrid',surface:'app shell',staticHooks:[{type:'contains',path:'App.tsx',text:'setImmersiveEditor(true)'},{type:'contains',path:'App.tsx',text:"AppState.addEventListener('change',apply)"}],deviceSteps:['Launch the app and note navigation visibility.','Send the app to background and return to foreground.','Repeat after opening and closing an editor.'],expected:'Configured immersive navigation is restored after foreground transitions without trapping the user in an unusable state.',evidence:'Short screen recording covering background/foreground and editor open/close.'},
  {id:'system.flow-layout-scaling',area:'system',title:'Flow layout scales across screen widths and font sizes',verification:'hybrid',surface:'V3 cards and metric grids',staticHooks:[{type:'file',path:'src/ui/FlowLayout.tsx'}],deviceSteps:['Test a narrow phone width and a large phone/tablet width.','Enable larger accessibility font scaling.','Inspect cards using each supported quick width.'],expected:'Cards wrap without overlap, preserve order, and remain readable at narrow/large widths and enlarged fonts.',evidence:'Screenshots for narrow, large, and accessibility-font cases.'},
  {id:'keyboard.last-input-visible',area:'keyboard',title:'Last input remains visible above IME',verification:'hybrid',surface:'ledger/dividend/calculator/settings/editor forms',staticHooks:[{type:'file',path:'src/ui/KeyboardAware.tsx'},{type:'contains',path:'src/ui/UniversalEditor.tsx',text:'KeyboardSafeFooter'}],deviceSteps:['Open the longest active form.','Focus the last editable field using Gboard or the OEM keyboard.','Scroll while the keyboard is open and rotate once if supported.'],expected:'The focused field and fixed action footer stay visible and reachable above the keyboard.',evidence:'Screenshots or recording showing the final input with the IME open.'},
  {id:'keyboard.rotation-large-font',area:'keyboard',title:'Keyboard avoidance survives rotation and large fonts',verification:'device',surface:'active form screens',staticHooks:[],deviceSteps:['Enable large system font scaling.','Open an active form and focus a lower field.','Rotate portrait to landscape and back while the IME is visible where device policy permits.'],expected:'No input becomes permanently hidden and the user can still reach Save/Cancel actions.',evidence:'Device/OS/font-scale notes with screenshots for portrait and landscape.'},
  {id:'editor.touch-long-list',area:'editor',title:'Universal Editor touch ergonomics and long-list scrolling',verification:'hybrid',surface:'Universal Editor',staticHooks:[{type:'file',path:'src/ui/UniversalEditor.tsx'}],deviceSteps:['Open Universal Editor from a registered node.','Expand sections with long content, including Effects and Advanced.','Scroll to the bottom, edit controls, then use Cancel/Reset/Save.'],expected:'Section headers, controls, scrolling, and fixed footer remain usable without accidental activation or unreachable content.',evidence:'Screen recording of a full top-to-bottom editor interaction.'},
  {id:'editor.native-serialization',area:'editor',title:'Settings inventory edits serialize to native renderers',verification:'hybrid',surface:'Settings → Special → Universal Editor',staticHooks:[{type:'file',path:'src/ui/universalRegistry.ts'},{type:'file',path:'src/services/floatingOverlay.ts'},{type:'file',path:'src/widgets/ProfitWidget.tsx'}],deviceSteps:['Edit a registered node used by Widget or floating overlay.','Save the edit from the app Settings inventory.','Refresh or reopen the target native surface.'],expected:'The native surface consumes the persisted node settings without requiring a React Native modal while the app is closed.',evidence:'Before/after screenshots of the editor setting and corresponding native surface.'},
  {id:'widget.paint-fallback',area:'widget',title:'Widget paint fallbacks remain readable',verification:'hybrid',surface:'Android launcher Widget',staticHooks:[{type:'file',path:'src/widgets/ProfitWidget.tsx'}],deviceSteps:['Apply theme/P&L colors and advanced effects to Widget-bound nodes.','Refresh the launcher Widget.','Check positive, negative, and neutral values.'],expected:'Unsupported paint/effect primitives degrade to readable fixed/P&L colors without losing semantic state.',evidence:'Launcher screenshots covering positive, negative, neutral, and at least one degraded effect.'},
  {id:'widget.update-click',area:'widget',title:'Widget refresh and click behavior',verification:'device',surface:'Android launcher Widget',staticHooks:[],deviceSteps:['Add the Widget to the launcher.','Trigger its supported refresh interaction and observe the update timestamp/data.','Use the configured open-app interaction.'],expected:'Refresh does not zero valid data, update feedback is visible, and the open-app interaction reaches the expected app destination.',evidence:'Screen recording from launcher refresh through app open.'},
  {id:'overlay.permission-policy',area:'overlay',title:'Floating overlay permission and OEM policy handling',verification:'hybrid',surface:'Android floating overlay',staticHooks:[{type:'file',path:'src/services/floatingOverlay.ts'}],deviceSteps:['Start with overlay permission denied.','Request permission and enable the floating monitor.','Background the app and observe behavior under the device OEM background policy.'],expected:'Permission denial is recoverable, enabling succeeds after permission grant, and OEM restrictions fail gracefully without corrupting app state.',evidence:'Permission-flow recording plus OEM/device notes.'},
  {id:'overlay.lifecycle',area:'overlay',title:'Floating overlay close, minimize, restore, drag and resize lifecycle',verification:'hybrid',surface:'Android floating overlay',staticHooks:[{type:'file',path:'modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingInvestmentBotService.kt'}],deviceSteps:['Open the floating monitor.','Drag and resize it, then minimize and restore it.','Close the window and reopen it from the app without restarting the service manually.'],expected:'Position/size interactions work, minimize/restore is stable, and close/reopen follows the configured lifecycle without stale or duplicated windows.',evidence:'Screen recording covering drag, resize, minimize, restore, close, and reopen.'},
  {id:'overlay.effect-fallback',area:'overlay',title:'Overlay advanced effects degrade compatibly',verification:'hybrid',surface:'Android floating overlay',staticHooks:[{type:'file',path:'modules/floating-investment-bot/android/src/main/java/com/etfpilot/floatingbot/FloatingInvestmentBotService.kt'}],deviceSteps:['Apply gradient/glow/shadow/shimmer/sweep capable node settings.','Open the native overlay.','Compare semantic colors and emphasis with the in-app editor preview.'],expected:'Native fallback preserves semantic color/emphasis and remains legible even where blur or continuous animation is unsupported.',evidence:'Side-by-side screenshots of editor preview and overlay.'},
  {id:'monitor-template.compact',area:'monitor-template',title:'Compact monitor templates fit bounded overlay sizes',verification:'hybrid',surface:'floating monitor compact family',staticHooks:[{type:'contains',path:'src/v3/monitorTemplates.ts',text:'MONITOR_TEMPLATES'}],deviceSteps:['Select each compact/small monitor template.','Test minimum supported overlay size.','Verify fixed header/body/summary/footer regions remain usable.'],expected:'Compact templates do not clip essential controls or overlap fixed regions at minimum supported size.',evidence:'One screenshot per compact template at minimum size.'},
  {id:'monitor-template.standard',area:'monitor-template',title:'Standard monitor templates render all configured fields',verification:'hybrid',surface:'floating monitor standard family',staticHooks:[{type:'contains',path:'src/v3/monitorTemplates.ts',text:'MONITOR_TEMPLATES'}],deviceSteps:['Select each standard monitor template.','Populate enough holdings/watchlist rows to require scrolling.','Verify title, status, body, and summary content.'],expected:'Standard templates render configured fields, scroll only the bounded body, and retain fixed header/summary/footer.',evidence:'One screenshot per standard template plus one scroll recording.'},
  {id:'monitor-template.large',area:'monitor-template',title:'Large/dense monitor templates remain usable across resize range',verification:'hybrid',surface:'floating monitor large/dense family',staticHooks:[{type:'contains',path:'src/v3/monitorTemplates.ts',text:'MONITOR_TEMPLATES'}],deviceSteps:['Select each large/dense template.','Resize from minimum to a large window size.','Verify rows, columns, controls, and summary at both extremes.'],expected:'Large/dense templates preserve readable columns and stable controls throughout the supported resize range.',evidence:'Minimum/maximum size screenshots for each large/dense template.'},
  {id:'watchlist.persistence-offline',area:'watchlist',title:'Watchlist persists independently across relaunch and offline state',verification:'hybrid',surface:'Home/watchlist/monitor candidate selection',staticHooks:[{type:'contains',path:'App.tsx',text:'watchlistSymbols'}],deviceSteps:['Add and reorder watchlist symbols that are not holdings.','Force-close and relaunch the app.','Repeat once with network unavailable.'],expected:'Watchlist membership/order persists without creating accounting holdings or ledger records, including offline relaunch.',evidence:'Before/after screenshots plus exported or inspected holding count showing no accounting row was created.'},
  {id:'watchlist.live-quotes-upgrade',area:'watchlist',title:'Watchlist quote subscriptions survive reconnect and app update',verification:'hybrid',surface:'Home/watchlist/monitor',staticHooks:[{type:'contains',path:'App.tsx',text:'watchlistSymbols'}],deviceSteps:['Keep at least one watchlist-only ETF visible.','Disconnect and reconnect the network and confirm quote recovery.','After a compatible update/relaunch, confirm watchlist-only symbols still subscribe without entering portfolio calculations.'],expected:'Watchlist-only symbols recover live quotes and remain display-only across reconnect/relaunch/update.',evidence:'Recording or timestamped screenshots before disconnect, after reconnect, and after relaunch/update.'},
  {id:'apk-matrix.preview-install',area:'apk-matrix',title:'Preview APK installs and launches on representative Android devices',verification:'device',surface:'Android APK',staticHooks:[],deviceSteps:['Build the approved preview APK outside this harness workflow.','Install on at least one gesture-navigation device and one three-button-navigation device or equivalent emulator profiles.','Launch, relaunch, and exercise core navigation.'],expected:'The preview APK installs, launches, persists state, and exposes no blocking native crash across the representative matrix.',evidence:'Build identifier plus device/OS matrix with install/launch result for each row.'},
  {id:'apk-matrix.package-health',area:'apk-matrix',title:'Expo/package compatibility is verified when tooling/network is available',verification:'device',surface:'project/package toolchain',staticHooks:[],deviceSteps:['Run expo-doctor and expo install --check with network/tooling available.','Record warnings/errors without auto-changing dependencies during acceptance.','Re-run TypeScript and acceptance preflight after any separately approved dependency correction.'],expected:'Package/tooling health is recorded explicitly; any dependency correction is handled as a separate reviewed change rather than silently folded into device evidence.',evidence:'Captured expo-doctor and expo install --check output with date and environment versions.'},
];

module.exports={version:'3.6.0',areas,items};
